# LiSTA DE NOMES E SOBRENOMES ALEMÃES ESTADOS E CIDADES

german_names=["Aaron","Abraham","Achim","Adalbert","Adam","Adelbert","Adolf","Adrian","Alban","Albert","Albrecht","Alex","Alexander","Alexis","Alfons","Alfred",
"Alois","Aloysius","Alwin","Amand","André","Andreas","Anselm","Ansgar","Anton","Arend","Armin","Arndt","Arne","Arnfried","Arnold","Arnulf","Arthur","Artur",
"August","Augustin","Aurel","Axel","Baldur","Baptist","Barnabas","Bartholomäus","Bastian","Ben","Benedikt","Benjamin","Benno","Bernd","Bernhard","Bert","Berthold",
"Bertram","Bjoern","Björn","Bonifaz","Boris","Bruno","Burchard","Burkhard","Burkhart","Carl","Carsten","Chris","Christian","Christoph","Claus","Clemens","Conrad",
"Corbinian","Cord","Cornelius","Dan","Daniel","David","Denis","Dennis","Detlef","Didi","Dierk","Dieter","Dietfried","Diethelm","Dietmar","Dietrich","Dirk",
"Dominik","Ebbe","Eberhard","Eckart","Eckbert","Eckehard","Eckhard","Eckhart","Edgar","Edmund","Eduard","Egon","Ekkehard","Ekkehardt","Elias","Elmo","Emanuel",
"Emil","Emmerich","Engel","Engelbert","Erdmann","Erhard","Eric","Erich","Erik","Ernst","Erwin","Eugen","Evelyn","Evert","Ewald","Fabian","Falk","Felix","Ferdi",
"Ferdinand","Fester","Fiete","Filibert","Finn","Finn","Florentin","Florian","Frank","Franz","Fred","Frej","Friedemann","Friedhelm","Friedhold","Friedrich",
"Fritz","Gabi","Gabriel","Gebbert","Gebhard","Geert","Georg","Gerald","Gerd","Gereon","Gerfried","Gerhard","Gerhardt","Gernot","Gero","Gerold","Gerolf","Gert",
"Gerulf","Gervas","Gilbert","Gisbert","Gottfried","Gotthard","Gotthilf","Gotthold","Gottlieb","Gottlob","Gregor","Guido","Günter","Gunter","Günther","Gunther",
"Guntram","Gustaf","Gustav","Hagen","Hanke","Hanne","Hannes","Hans","Harald","Hartmann","Hartmut","Hartwig","Hartwin","Heike","Heiko","Heiner","Heino","Heinrich",
"Heinz","Helfried","Helge","Helmfried","Helmut","Helmuth","Hendrik","Henning","Henrik","Herbert","Heribert","Hermann","Hermenegild","Hieronymus","Hilbert",
"Hildebert","Hinrich","Holger","Horst","Hubert","Hubertus","Hugo","Humbert","Huppert","Ignatz","Immanuel","Inge","Ingo","Ingolf","Ingomar","Isaak","Isidor",
"Ivo","Jakob","Jan","Jeremias","Jo","Joachim","Jochem","Jochen","Jochim","Johan","Johann","Johannes","Jonas","Jonatan","Jonathan","Jörg","Josef","Joseph",
"Julian","Julius","Jürgen","Justus","Kai","Karl","Karlmann","Karsten","Kasimir","Kaspar","Kay","Kayetan","Kevin","Kilian","Klaas","Klaus","Klemens","Knut",
"Kolman","Koloman","Konrad","Konstantin","Korbinian","Körbl","Kord","Kunibert","Kuno","Kurt","Lambert","Lammert","Lanzo","Lars","Laurenz","Leberecht","Lennart",
"Lenz","Leo","Leon","Leonard","Leonhard","Leopold","Levi","Liam","Linus","Lorenz","Lothar","Luca","Ludger","Ludolf","Ludwig","Luitger","Luitpold","Lukas",
"Lutz","Malte","Malthe","Manfred","Manfried","Manu","Manuel","Marcel","Marcell","Marcellus","Marco","Mario","Marius","Markus","Martin","Marvin","Marwin",
"Marzell","Mathias","Mathis","Matthäus","Matthias","Mattias","Max","Maximilian","Meinard","Meine","Meinhard","Meino","Meinrad","Menno","Merten","Michael",
"Michel","Michi","Moritz","Mose","Nickolaus","Nico","Nicolaus","Niklas","Niko","Nikolaus","Noah","Norbert","Olaf","Oliver","Ortwin","Oskar","Oswald","Othmar",
"Otmar","Ottmar","Otto","Ottokar","Ottomar","Pankraz","Parsifal","Pascal","Patrick","Paul","Peter","Petrus","Philipp","Poldi","Quirin","Rafael","Raffael",
"Raimund","Rainer","Ralf","Ralph","Raphael","Reimund","Rein","Reiner","Reinhard","Reinhold","René","Richard","Robert","Rochus","Rodolf","Roger","Roland",
"Rolf","Roman","Ronald","Rudi","Rüdiger","Rudolf","Rupert","Samuel","Sascha","Sebastian","Sepp","Seppel","Severin","Siegbert","Siegfried","Sieghard","Siegmund",
"Siegward","Sigi","Sigismund","Sigmund","Silvester","Simon","Sören","Stefan","Steffen","Stephan","Sven","Sylvester","Theo","Theodor","Theophil","Thiemo",
"Thilo","Thomas","Thorben","Thorsten","Till","Tillo","Tilo","Tim","Timo","Timotheus","Tobias","Tom","Toni","Torben","Torsten","Traugott","Udo","Ulf","Ulrich",
"Urban","Urs","Utz","Uwe","Valentin","Veit","Vester","Viktor","Vinzent","Vinzenz","Volker","Waldemar","Waldo","Walter","Walther","Wendel",
"Wenzel","Wenzeslaus","Werner","Werther","Wessel","Wetzel","Wiebe","Wieland","Wilfried","Wilhelm","Willi","Willy","Wim","Winfried","Witold","Wolf","Wolfgang",
"Wolfram","Wulf","Xaver","Yvo",
]

german_surnames=["Müller","Schmidt","Schneider","Fischer","Weber","Meyer","Wagner","Becker","Schulz","Hoffmann","Koch",
"Richter","Bauer","Schäfer","Klein","Wolf","Schröder","Neumann","Schwarz","Braun","Zimmermann","Hofmann","Lange","Hartmann",
"Krüger","Krause","Lehmann","Schmitz","Meier","Schmitt","Werner","Schmid","Schulze","Maier","Herrmann","Mayer","Köhler","Walter",
"König","Huber","Kaiser","Peters","Fuchs","Möller","Lang","Scholz","Jung","Weiß","Hahn","Keller","Berger","Vogel","Schubert","Friedrich",
"Frank","Roth","Winkler","Beck","Günther","Lorenz","Baumann","Franke","Albrecht","Ludwig","Winter","Simon","Schuster","Schumacher",
"Kraus","Böhm","Vogt","Martin","Stein","Jäger","Sommer","Krämer","Brandt","Otto","Heinrich","Schulte","Graf","Haas","Seidel",
"Schreiber","Groß","Dietrich","Engel","Ziegler","Horn","Bergmann","Pohl","Kuhn","Jansen","Voigt","Kühn","Beyer","Busch","Thomas",
"Hansen","Lindner","Arnold","Sauer","Kramer","Wolff","Seifert","Hübner","Ernst","Pfeiffer","Wenzel","Franz","Nagel","Kern","Barth",
"Peter","Götz","Paul","Hermann","Kruse","Riedel","Ott","Haase","Petersen","Langer","Lenz","Grimm","Hoppe","Bock","Arndt","Jahn","Wilhelm","Mohr",
"Ritter","Schumann","Fiedler","Kaufmann","Kraft","Förster","Berg","Thiel","Miller","Michel","Marx","Walther","Lutz","Sander","Fritz",
"Eckert","Thiele","Böttcher","Reuter","Reinhardt","Schilling","Schindler","Frey","Hein","Ebert","Hesse","Behrens","Schütz","Kunz",
"Schramm","Herzog","Rudolph","Gruber","Bayer","Kunze","Witt","Fröhlich","Nowak","Geiger","Stephan","Maurer","Bender","Seitz","Schultz","Bachmann","Adam","Brinkmann","Fink","Kirchner","Stahl","Ullrich","Gerlach","Breuer","Steiner","Gärtner","Büttner","Dietz",
"Scherer","Bruns","Kurz","Naumann","Moser","Brand","Böhme","Reichert","Schlüter","Ulrich","Löffler","Binder","Janssen","Heinz","Wendt",
"Blum","Körner","Brunner","Schenk","Wegner","Schwab","Menzel","Urban","Schröter","Krebs","Göbel","Heller","Stark","Buchholz","Wirth",
"Döring","Weiss","Kopp","Rieger","Link","Hinz","John","Bartsch","Meißner","Reimann","Wilke","Hildebrandt","Unger","Hirsch","Bischoff",
"Jakob","Rose","Pfeifer","Ackermann","Rohde","Schiller","Sturm","Köster","Hennig","Bach","Freitag","Witte","Engelhardt","Kröger","Marquardt",
"Fricke","Ahrens","Lemke","Wittmann","Linke","Siebert","Vetter","Kohl","Kolb","Henning","Heinze","Noack","Gebhardt","Renner","Reich",
"Baier","Nickel","Funk","Keil","Erdmann","Kremer","Mertens","Pieper","Martens","Berndt","Hanke","Baum","Held","Will","Münch","Conrad",
"Kiefer","Bartels","Hammer","Esser","Harms","Henke","Mann","Fuhrmann","Schlegel","Stoll","Kirsch","Wiese","Jacob","Herbst","Decker",
"Klose","Hamann","Henkel","Brückner","Dittrich","Schrader","Neubauer","Heine","Nolte","Krug","Stadler","Niemann","Janßen","Krieger",
"Kuhlmann","Kluge","Adler","Karl","Röder","Wiedemann","Konrad","Schön","Philipp","Lindemann","Burkhardt","Blank","Hauser","Großmann","Zimmer",
"Kühne","Wahl","Fritsch","Bader","Klaus","Popp","Steffen","Heinemann","Strauß","Funke","Bernhardt","Preuß","Zander","Albert","Lohmann",
"Mayr","Anders","Haupt","Hummel","Brenner","Probst","Baur","Beier","Jost","Hartung","Burger","Feldmann","Bode","Vollmer","Jordan","Herold","Wetzel",
"Rothe","Fleischer","Behrendt","Wiegand","Jacobs","Rauch","Wild","Knoll","Wegener","Straub","Hohmann","Voß","Merz","Reiter","Christ","Haag",
"Gross","Neubert","Reichel","Schüler","Strobel","Albers","Beer","Diehl","Ehlers","Krauß","Betz","Hagen","Rupp","Heck","Schade","Kroll",
"Weise","Schütte","Hentschel","Stock","Benz","Rausch","Wulf","Metz","Rapp","Zeller","Altmann","Steffens","Block","Geißler","Weis","Moritz",
"Falk","Freund","Eder","Meister","Wunderlich","Kessler","Seiler","Giese","Merkel","Dörr","Bittner","Sonntag","Jürgens","Römer","Gerber",
"Hartwig","Wieland","Heuer","Gottschalk","Bertram","Born","Buck","Lauer","Raab","Seeger","Hinrichs","Völker","Timm","Heil","Schweizer",
"Bühler","Pape","Pietsch","Gabriel","Hiller","Runge","Kellner","Eichhorn","Scharf","Schaefer","Bär","Wichmann","Greiner","Eberhardt",
"Keßler","Hempel","Engelmann","Mueller","Appel","Engels","Weigel","Moll","Geyer","Opitz","Neuhaus","Hecht","Schütze","Wiesner","Winkelmann",
"Mack","Radtke","Dorn","Seidl","Lechner","Hensel","Heise","Klemm","Brüggemann","Weidner","Heim","Eggert","Brandl","Scheffler","Forster",
"Hagemann","Geisler","Sauter","Eichler","Schuler","Barthel","Schott","Auer","Michels","Specht","Reimer","Stumpf","Fleischmann","Neugebauer",
"Kretschmer","Steinbach","Gebauer","Brauer","Wirtz","Springer","Bremer","May","Otte","Noll","Dreyer","Sievers","Siegel","Weller","Cordes",
"Prinz","Schroeder","Walz","Schürmann","Schnell","Kohler","Schaller","Börner","Baumgartner","Singer","Drescher","Finke","Evers","Gerhardt",
"Frenzel","Horstmann","Scholl","Rath","Uhlig","Mielke","Kühl","Schick","Junker","Harder","Hausmann","Riedl","Klotz","Gerdes","Dittmann",
"Biermann","Stolz","Maas","Kranz","Langner","Haug","Michaelis","Große","Rother","Kahl","Heitmann","Eggers","Faust","Jensen","Bürger",
"Volk","Kemper","Maaß","Pfaff","Elsner","Petzold","Nguyen","Eberle","Schütt","Kasper","Haller","Schnabel","Faber","Rösch","Geier","Rabe",
"Dick","Pütz","Höhne","Schirmer","Reichelt","Groth","Kempf","Drews","Thieme","Fritzsche","Wittig","Dürr","Fries","Junge","Knapp","Abel",
"Koller","Endres","Kilian","Thoma","Matthes","Ehrhardt","Paulus","Behr","Rademacher","Hauck","Heinrichs","Bohn","Jahnke","Thomsen","Bahr",
"Lück","Korn","Wehner","Schober","Janke","Hecker","Dreher","Rau","Sattler","Helbig","Ullmann","Rost","Melzer","Schaaf","Weiler",
"Eckhardt","Reinhold","Hellwig","Leonhardt","Brockmann","Klug","Bernhard","Klinger","Blume","Westermann","Hildebrand","Hering","Lippert",
"Heinen","Hellmann","Just","Lehner","Pilz","Heimann","Sperling","Knorr","Sprenger","Trautmann","Wacker","Pohlmann","Friedrichs","Huth",
"Wessel","Theis","Stöhr","Heilmann","Sieber","Claus","Höfer","Grote","Rudolf","Augustin","Wille","Wolters","Gehrke","Böhmer","Hartl",
"Liedtke","Burmeister","Renz","Kunkel","Vogler","Schwarze","Ries","Kirchhoff","Hofer","Balzer","Stenzel","Hornung","Korte","Teichmann",
"Amann","Höhn","Hertel","Strauch","Kretzschmar","Vogl","Clemens","Lohse","Schreiner","Nitsche","Wagener","Lotz","Kaminski","Bosch","Hoyer",
"Schweiger","Starke","Schönfeld","Bartel","Klatt","Oppermann","Metzger","Seemann","David","Nitschke","Schwarzer","Hafner","Henze","Lampe",
"Schöne","Roos","Engler","Kock","Diekmann","Krieg","Hess","Rehm","Reinhard","Otten","Holz","Schleicher","Menke","Heß","Kersten","Eisele",
"Zink","Wilde","Ruppert","Voss","Mader","Lehnert","Veit","Behnke","Cremer","Trapp","Heckmann","Grau","Baumeister","Grundmann","Hampel","Rößler",
"Hagedorn","Baumgart","Stiller","Scheer","Ehlert","Küster","Kolbe","Heyer","Petri","Heider","Orth","Pfeffer","Sachs","Späth","Yilmaz","Brandes",
"Ulbrich","Pfister","Frick","Reinke","Wörner","Loos","Kleine","Keck","Steinert","Brüning","Buschmann","Schweitzer","Ostermann","Daniel","Schuh",
"Kirschner","Brendel","Tietz","Widmann","Baumgärtner","Michael","Becher","Hermes","Ebner","Wendel","Thies","Muth","Wulff","Fritsche","Reiß",
"Kastner","Schwabe","Mende","Horst","Johannsen","Schüller","Heuser","Jakobs","Jaeger","Reitz","Ewald","Niemeyer","Stamm","Rühl","Kling",
"Hannemann","Wilms","Helm","Mai","Cramer","Kühnel","Riemer","Jacobi","Weiland","Apel","Rode","Doll","Schmidtke","Adams","Knobloch","Hille",
"Merten","Buchner","Küpper","Seibert","Haack","Eckstein","Hölscher","Janzen","Fürst","Hager","Budde","Baumgarten","Steinke","Gehrmann",
"Glaser","Hacker","Bastian","Schwartz","Köhn","Schiffer","Eckardt","Tiedemann","Heidenreich","Kugler","Böttger","Krohn","Ebeling","Lorenzen",
"Volz","Volkmann","Eilers","Schell","Gehring","Schauer","Reinecke","Mühlbauer","Berthold","Hanisch","Mahler","Büchner","Ebel",
"Weinert","Thelen","Stern","Grund","Heidrich","Burghardt","Gottwald","Gläser","Pabst","Resch","Reiser","Wieczorek","Spies","Löhr",
"Hillebrand","Hamm","Jonas","Schröer","Ortmann","Thiemann","Pauli","Busse","Kowalski","Schaper","Scheel","Friedl","Lukas","Kübler","Sachse",
"Morgenstern","Ahlers","Dieckmann","Pahl","Meurer","Frisch","Hardt","Clausen","Ewert","Obermeier","Stratmann","Schultze","Reimers",
"Rahn","Holst","Bormann","Petermann","Henn","Homann","Ochs","Enders","Herz","Körber","Paulsen","Küppers","Berner","Kellermann","Seidler","Schaub","Häusler","Brück",
"Scheller","Boldt","Emmerich","Rogge","Hill","Armbruster","Spindler","Rupprecht","Grube","Hinze","Mangold","Dietze","Grün","Kunert","Hans","Sailer","Zeidler",
"Tillmann","Hoff","Sommerfeld","Brehm","Kratz","Lerch","Grabowski","Palm","Grunwald","Lauterbach","Hopp","Knauer","Ehrlich","Bolz","Kreuzer","Hermanns",
"Bucher","Raabe","Petry","Hollmann","Drechsler","Friese","Christiansen","Wilkens","Wessels","Bosse","Bräuer","Reif","Exner","Fechner","Kummer","Fichtner",
"Andres","Wüst","Linder","Lüdtke","Büscher","Finger","Reis","Merk","Aigner","Rösler","Goebel","Franzen","Grünewald","Struck","Siegert","Kleinert","Welsch",
"Hoch","Habermann","Fiebig","Seibel","Zorn","Dreier","Heidemann","Zöller","Henrich","Bruhn","Wächter","Weigand","Metzner","Freese","Hopf","Pusch","Weiser","Boos",
]

german_citys = [
        "Karlsruhe","Mannheim","Freiburg","Heidelberg","Pforzheim","München","Nürnberg","Augsburg","Würzburg","Regensburg","Bremen",
        "Braunschweig","Wolfsburg","Salzgitter","Wolfenbüttel","Helmstedt","Hamburgo","Frankfurt","Wiesbaden","Kassel","Darmstadt","Offenbach",
        "Oldenburg","Wilhelmshaven","Delmenhorst","Lüneburg","Emden","Rostock","Schwerin","Neubrandenburg","Stralsund","Wismar",
        "Detmold","Lemgo","Bad Salzuflen","Lage","Bad Oeynhausen","Westfalen","Dortmund","Essen","Bochum","Duisburg","Münster",
        "Königsberg ","Tilsit ","Insterburg ","Allenstein ","Pillau","Szczecin","Stargard","Greifswald","Stralsund","Kołobrzeg",
        "Poznań","Gniezno","Leszno","Kalisz","Pleszew","Köln","Düsseldorf","Bonn","Duisburg","Essen","Mainz","Ludwigshafen","Koblenz","Trier","Kaiserslautern",
        "Saarbrücken","Völklingen","Neunkirchen","Homburg","St. Wendel","Dresden","Leipzig","Chemnitz","Zwickau","Plauen",
        "Magdeburg","Halle","Dessau","Wittenberg","Merseburg","Kiel","Flensburg","Lübeck","Neumünster","Itzehoe","Schleswig ","Haderslev","Aabenraa","Tønder","Sønderborg",
        "Rudolstadt","Sondershausen","Arnstadt","Ilmenau","Bad Blankenburg","Erfurt","Jena","Gera","Weimar","Gotha",
        "Dortmund","Essen","Bochum","Duisburg","Münster","Stuttgart","Mannheim","Karlsruhe","Ulm","Heilbronn","Wien","Graz","Linz","Salzburgo","Innsbruck",
        "Reichenberg ","Aussig ","Karlsbad ","Troppau ","Asch",        
]   
