# LiSTA DE NOMES E SOBRENOMES AMERICANOS ESTADOS E CIDADES

american_names = ["Aaren","Aaron","Abe","Abel","Abner","Abraham","Abram","Ace","Adair","Adam","Addison","Aden","Adolph","Adrian","Aidan","Aiden","Ainsley",
"Al","Alan","Alban","Albert","Albin","Alden","Aldous","Alec","Alex","Alexander","Alexis","Alf","Alfie","Alfred","Algar","Alger","Algernon","Allan","Allen",
"Allyn","Aloysius","Alpha","Alphonso","Alphonzo","Alton","Alva","Alvin","Ambrose","Amery","Amias","Amos","Amyas","Anderson","Andie","Andre","Andrew","Andy","Angel",
"Angus","Ansel","Anselm","Anson","Anthony","Anton","Antony","Archibald","Archie","Arden","Aric","Ariel","Arlen","Arlie","Arlo","Arn","Arnie","Arnold",
"Arron","Art","Arthur","Arvel","Ash","Asher","Ashley","Ashton","Aston","Astor","Auberon","Aubrey","Audley","August","Augustine","Austen","Austin","Austyn",
"Averill","Avery","Axel","Aydan","Ayden","Aylmer","Azaria","Bailey","Baldwin","Balfour","Barclay","Barnabas","Barney","Barret","Barrett","Barrie","Barry",
"Bart","Bartholomew","Basil","Baxter","Beau","Beaumont","Beauregard","Ben","Benedict","Benj","Benjamin","Benji","Benjy","Bennett","Bennie","Benny","Benson",
"Bentley","Benton","Bernard","Bernie","Berny","Berry","Bert","Bertie","Bertram","Bertrand","Bevan","Beverly","Bevis","Biff","Bill","Billie","Billy","Bishop",
"Blaine","Blair","Blake","Blaze","Blythe","Bob","Bobbie","Bobby","Boniface","Booker","Boyce","Boyd","Gage","Gale","Galen","Gallagher","Garfield","Garland",
"Garnet","Garnett","Garret","Garrett","Garrick","Garry","Garth","Gary","Gavin","Gayelord","Gayle","Gaylord","Geffrey","Gene","Geoff","Geoffrey","Geordie",
"George","Georgie","Gerald","Gerard","German","Gerrard","Gerry","Gervase","Gib","Gideon","Giffard","Gil","Gilbert","Giles","Gilroy","Gladwin","Gladwyn",
"Glanville","Glen","Glenn","Goddard","Godfrey","Goodwin","Gord","Gorden","Gordie","Gordon","Gordy","Gore","Grady","Graeme","Graham","Grahame","Grant",
"Granville","Gray","Grayson","Greer","Greg","Gregg","Gregory","Grenville","Gresham","Grey","Greyson","Grier","Griffin","Grosvenor","Grover","Gus","Guy",
"Gyles","Hadley","Hadyn","Hal","Hale","Hall","Hallam","Hamilton","Hammond","Hank","Happy","Harding","Hardy","Harlan","Harland","Harley","Harlow","Harmon",
"Harold","Harper","Harris","Harrison","Harry","Hartley","Harve","Harvey","Harvie","Haven","Hayden","Haywood","Headley","Heath","Hector","Hedley","Henderson",
"Henry","Herb","Herbert","Herbie","Herman","Herschel","Hershel","Hervey","Hewie","Hiram","Holden","Hollis","Homer","Horace","Horatio","Howard","Howie",
"Hoyt","Hubert","Hudson","Huey","Hugh","Hughie","Hugo","Humbert","Humphrey","Humphry","Hunter","Hyram","Ian","Iggy","Ike","Ilbert","Indiana","Indigo",
"Ingram","Inigo","Ira","Irvin","Irvine","Irving","Irwin","Isaac","Isador","Isadore","Isaiah","Isiah","Isidore","Israel","Issac","Issy","Ivan","Izzy",
"Jace","Jack","Jackie","Jackson","Jacob","Jade","Jaden","Jadyn","Jaiden","Jake","James","Jamey","Jamie","Jamison","Jared","Jarod","Jaron","Jarred","Jarrett",
"Jarrod","Jarvis","Jason","Jasper","Jaxon","Jaxson","Jay","Jayce","Jaycob","Jayden","Jaydon","Jaylen","Jaylin","Jaymes","Jayson","Jeb","Jed","Jeff","Jefferson",
"Jeffery","Jeffrey","Jeffry","Jem","Jemmy","Jepson","Jerald","Jere","Jeremiah","Jeremy","Jericho","Jermaine","Jerold","Jerome","Jerrard","Jerred","Jerrod",
"Jerrold","Jerry","Jervis","Jess","Jesse","Jessie","Jett","Jewel","Jewell","Jim","Jimi","Jimmie","Jimmy","Jo","Joby","Jody","Joe","Joel","Joey","John",
"Johnathan","Johnathon","Johnie","Johnnie","Johnny","Jojo","Jolyon","Jon","Jonah","Jonathan","Jonathon","Jonny","Jools","Jordan","Jordon","Joseph","Josh",
"Joshua","Josiah","Joss","Joyce","Judd","Jude","Jules","Julian","Julius","Julyan","Junior","Justice","Justin","Justy","Kade","Kaden","Kaeden","Kaiden","Kaleb",
"Kam","Kameron","Kane","Kaolin","Karl","Kasey","Kayden","Kean","Keane","Keaton","Keefe","Keegan","Kegan","Keiran","Keith","Kelan","Kelcey","Kelley","Kelly",
"Kelsey","Kelvin","Kemp","Ken","Kendal","Kendall","Kendrick","Kenelm","Kenith","Kennard","Kennedy","Kenneth","Kennith","Kenny","Kenrick","Kent","Kenton",
"Kenyon","Kenzie","Kermit","Kerry","Kester","Kev","Kevan","Kevin","Kevyn","Kian","Kiaran","Kiefer","Kieran","Kieron","Kim","Kimball","King","Kingsley",
"Kingston","Kip","Kipling","Kirby","Kirk","Kit","Knox","Koby","Kodey","Kody","Kolby","Kole","Konnor","Korbin","Korey","Kory","Kris","Kristopher","Kurt",
"Kurtis","Kyle","Kyler","Kynaston","Lacey","Lachlan","Lacy","Laird","Lake","Lamar","Lambert","Lamont","Lance","Landen","Landon","Lane","Lanford","Langdon",
"Lanny","Larrie","Larry","Lauren","Laurence","Robbie","Robby","Robert","Robin","Rocky","Rod","Roddy","Roderick","Rodge","Rodger","Rodney","Rodolph","Roger",
"Roland","Rolf","Rolland","Rollo","Rolo","Rolph","Roly","Roman","Ron","Ronald","Ronnie","Ronny","Roosevelt","Rorie","Rory","Roscoe","Ross","Roswell","Rowan",
"Rowland","Rowley","Roy","Royal","Royale","Royce","Roydon","Royle","Rube","Rudolph","Rudy","Rudyard","Rufus","Rupert","Russ","Russel","Russell","Rusty","Ryan",
"Ryder","Ryker","Rylan","Ryley","Sacheverell","Sage","Sal","Sam","Sammie","Sammy","Sampson","Samson","Samuel","Sandford","Sandy","Sanford","Sasha","Satchel",
"Sawyer","Saxon","Schuyler","Scot","Scott","Scottie","Scotty","Sean","Sebastian","Sefton","Selby","Selwyn","September","Sequoia","Seth","Seward","Seymour",
"Shad","Shane","Shannon","Shanon","Shaquille","Shaun","Shawn","Shayne","Sheard","Shel","Shelby","Sheldon","Shelley","Shelly","Shelton","Sheridan","Sherman",
"Sherwood","Shirley","Sid","Sidney","Sigmund","Silas","Silver","Silvester","Simon","Sinclair","Skylar","Skyler","Slade","Sly","Smith","Solomon","Sonnie",
"Sonny","Sparrow","Spencer","Spike","Stace","Stacey","Stacy","Stafford","Stan","Stanford","Stanley","Ste","Steph","Stephen","Sterling","Steve","Steven",
"Stevie","Stew","Stewart","Stirling","Storm","Stu","Stuart","Sullivan","Syd","Sydney","Sylvester","Tad","Taegan","Talbot","Talon","Tanner","Tate","Tatton",
"Tayler","Taylor","Teagan","Ted","Teddy","Temple","Tennyson","Terance","Terell","Terence","Terrance","Terrell","Terrence","Terry","Terry","Tex","Thad","Thaddeus",
"Thane","Theo","Theobald","Theodore","Thom","Thomas","Thorburn","Thorley","Thornton","Thurstan","Tibby","Tiger","Tim","Timmy","Timothy","Titus","Tobias",
"Tobin","Toby","Tod","Todd","Tom","Tommie","Tommy","Tony","Topher","Torin","Trace","Tracey","Tracy","Trafford","Tranter","Travers","Travis","Trent","Trenton",
"Trev","Trevelyan","Trevor","Trey","Tristan","Tristen","Tristin","Triston","Troy","Trueman","Truman","Tucker","Ty","Tye","Tylar","Tyler","Tylor","Tyrell",
"Tyron","Tyrone","Tyrrell","Tyson","Ulric","Ulysses","Upton","Val","Valentine","Van","Vance","Vaughan","Vaughn","Vere","Vergil","Vern","Vernon","Vic","Victor",
"Vin","Vinal","Vince","Vincent","Vinnie","Vinny","Virgil","Wade","Waldo","Walker","Wallace","Wallis","Wally","Walt","Walter","Walton","Ward","Wardell",
"Warner","Warren","Warrick","Warwick","Washington","Wat","Wayland","Waylon","Wayne","Webster","Weldon","Wendell","Wes","Wesley","Westley","Weston","Whitaker",
"Whitney","Wil","Wilbur","Wilburn","Wiley","Wilf","Wilford","Wilfred","Wilfrid","Wilkie","Will","Willard","William","Willie","Willis","Willoughby","Willy",
"Wilmer","Wilson","Wilton","Windsor","Winfred","Winslow","Winston","Winthrop","Winton","Wisdom","Wolf","Wolfe","Woodrow","Woody","Wright","Wyatt","Wynne",
"Wystan","Xander","Xavier","Xavior","Xzavier","Yale","Yancy","Yorick","York","Zac","Zach","Zachariah","Zachary","Zachery","Zack","Zackary","Zackery","Zak",
"Zander","Zane","Zavier","Zechariah",
]

american_surnames = ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Wilson",
"Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson","Walker",
"Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter",
"Roberts","Gomez","Phillips","Evans","Turner","Diaz","Parker","Cruz","Edwards","Collins","Reyes","Stewart","Morris","Morales","Murphy","Cook","Rogers",
"Gutierrez","Ortiz","Morgan","Cooper","Peterson","Bailey","Reed","Kelly","Howard","Ramos","Kim","Cox","Ward","Richardson","Watson","Brooks","Chavez",
"Wood","James","Bennett","Gray","Mendoza","Ruiz","Hughes","Price","Alvarez","Castillo","Sanders","Patel","Myers","Long","Ross","Foster","Jimenez",
"Powell","Jenkins","Perry","Russell","Sullivan","Bell","Coleman","Butler","Henderson","Barnes","Gonzales","Fisher","Vasquez","Simmons","Romero",
"Jordan","Patterson","Alexander","Hamilton","Graham","Reynolds","Griffin","Wallace","Moreno","West","Cole","Hayes","Bryant","Herrera","Gibson","Ellis",
"Tran","Medina","Aguilar","Stevens","Murray","Ford","Castro","Marshall","Owens","Harrison","Fernandez","Mcdonald","Woods","Washington","Kennedy","Wells",
"Vargas","Henry","Chen","Freeman","Webb","Tucker","Guzman","Burns","Crawford","Olson","Simpson","Porter","Hunter","Gordon","Mendez","Silva","Shaw","Snyder",
"Mason","Dixon","Munoz","Hunt","Hicks","Holmes","Palmer","Wagner","Black","Robertson","Boyd","Rose","Stone","Salazar","Fox","Warren","Mills","Meyer",
"Rice","Schmidt","Garza","Daniels","Ferguson","Nichols","Stephens","Soto","Weaver","Ryan","Gardner","Payne","Grant","Dunn","Kelley","Spencer",
"Hawkins","Arnold","Pierce","Vazquez","Hansen","Peters","Santos","Hart","Bradley","Knight","Elliott","Cunningham","Duncan","Armstrong","Hudson","Carroll",
"Lane","Riley","Andrews","Alvarado","Ray","Delgado","Berry","Perkins","Hoffman","Johnston","Matthews","Pena","Richards","Contreras","Willis","Carpenter",
"Lawrence","Sandoval","Guerrero","George","Chapman","Rios","Estrada","Ortega","Watkins","Greene","Nunez","Wheeler","Valdez","Harper","Burke","Larson",
"Santiago","Maldonado","Morrison","Franklin","Carlson","Austin","Dominguez","Carr","Lawson","Jacobs","Obrien","Lynch","Singh","Vega","Bishop","Montgomery",
"Oliver","Jensen","Harvey","Williamson","Gilbert","Dean","Sims","Espinoza","Howell","Li","Wong","Reid","Hanson","Le","Mccoy","Garrett","Burton","Fuller",
"Wang","Weber","Welch","Rojas","Lucas","Marquez","Fields","Park","Yang","Little","Banks","Padilla","Day","Walsh","Bowman","Schultz","Luna","Fowler","Mejia",
"Davidson","Acosta","Brewer","May","Holland","Juarez","Newman","Pearson","Curtis","Cortez","Douglas","Schneider","Joseph","Barrett","Navarro","Figueroa",
"Keller","Avila","Wade","Molina","Stanley","Hopkins","Campos","Barnett","Bates","Chambers","Caldwell","Beck","Lambert","Miranda","Byrd","Craig","Ayala",
"Lowe","Frazier","Powers","Neal","Leonard","Gregory","Carrillo","Sutton","Fleming","Rhodes","Shelton","Schwartz","Norris","Jennings","Watts","Duran",
"Walters","Cohen","Mcdaniel","Moran","Parks","Steele","Vaughn","Becker","Holt","Deleon","Barker","Terry","Hale","Leon","Hail","Benson","Haynes","Horton",
"Miles","Lyons","Pham","Graves","Bush","Thornton","Wolfe","Warner","Cabrera","Mckinney","Mann","Zimmerman","Dawson","Lara","Fletcher","Page","Mccarthy","Love",
"Robles","Cervantes","Solis","Erickson","Reeves","Chang","Klein","Salinas","Fuentes","Baldwin","Daniel","Simon","Velasquez","Hardy","Higgins","Aguirre",
"Lin","Cummings","Chandler","Sharp","Barber","Bowen","Ochoa","Dennis","Robbins","Liu","Ramsey","Francis","Griffith","Paul","Blair","Oconnor","Cardenas",
"Pacheco","Cross","Calderon","Quinn","Moss","Swanson","Chan","Rivas","Khan","Rodgers","Serrano","Fitzgerald","Rosales","Stevenson","Christensen","Manning","Gill",
"Curry","Mclaughlin","Harmon","Mcgee","Gross","Doyle","Garner","Newton","Burgess","Reese","Walton","Blake","Trujillo","Adkins","Brady","Goodman","Roman",
"Webster","Goodwin","Fischer","Huang","Potter","Delacruz","Montoya","Todd","Wu","Hines","Mullins","Castaneda","Malone","Cannon","Tate","Mack","Sherman",
"Hubbard","Hodges","Zhang","Guerra","Wolf","Valencia","Saunders","Franco","Rowe","Gallagher","Farmer","Hammond","Hampton","Townsend","Ingram","Wise",
"Gallegos","Clarke","Barton","Schroeder","Maxwell","Waters","Logan","Camacho","Strickland","Norman","Person","Colon","Parsons","Frank","Harrington",
"Glover","Osborne","Buchanan","Casey","Floyd","Patton","Ibarra","Ball","Tyler","Suarez","Bowers","Orozco","Salas","Cobb","Gibbs","Andrade","Bauer","Conner",
"Moody","Escobar","Mcguire","Lloyd","Mueller","Hartman","French","Kramer","Mcbride","Pope","Lindsey","Velazquez","Norton","Mccormick","Sparks","Flynn",
"Yates","Hogan","Marsh","Macias","Villanueva","Zamora","Pratt","Stokes","Owen","Ballard","Lang","Brock","Villarreal","Charles","Drake","Barrera","Cain",
"Patrick","Pineda","Burnett","Mercado","Santana","Shepherd","Bautista","Ali","Shaffer","Lamb","Trevino","Mckenzie","Hess","Beil","Olsen","Cochran","Morton",
"Nash","Wilkins","Petersen","Briggs","Shah","Roth","Nicholson","Holloway","Lozano","Rangel","Flowers","Hoover","Short","Arias","Mora","Valenzuela",
"Bryan","Meyers","Weiss","Underwood","Bass","Greer","Summers","Houston","Carson","Morrow","Clayton","Whitaker","Decker","Yoder","Collier","Zuniga",
"Carey","Wilcox","Melendez","Poole","Roberson","Larsen","Conley","Davenport","Copeland","Massey","Lam","Huff","Rocha","Cameron","Jefferson","Hood","Monroe",
"Anthony","Pittman","Huynh","Randall","Singleton","Kirk","Combs","Mathis","Christian","Skinner","Bradford","Richard","Galvan","Wall","Boone","Kirby",
"Wilkinson","Bridges","Bruce","Atkinson","Velez","Meza","Roy","Vincent","York","Hodge","Villa","Abbott","Allison","Tapia","Gates","Chase","Sosa","Sweeney",
"Farrell","Wyatt","Dalton","Horn","Barron","Phelps","Yu","Dickerson","Heath","Foley","Atkins","Mathews","Bonilla","Acevedo","Benitez","Zavala","Hensley",
"Glenn","Cisneros","Harrell","Shields","Rubio","Huffman","Choi","Boyer","Garrison","Arroyo","Bond","Kane","Hancock","Callahan","Dillon","Cline","Wiggins",
"Grimes","Arellano","Melton","Oneill","Savage","Ho","Beltran","Pitts","Parrish","Ponce","Rich","Booth","Koch","Golden","Ware","Brennan","Mcdowell","Marks",
"Cantu","Humphrey","Baxter","Sawyer","Clay","Tanner","Hutchinson","Kaur","Berg","Wiley","Gilmore","Russo","Villegas","Hobbs","Keith","Wilkerson","Ahmed",
"Beard","Mcclain","Montes","Mata","Rosario","Vang","Walter","Henson","Oneal","Mosley","Mcclure","Beasley","Stephenson","Snow","Huerta","Preston","Vance",
"Barry","Johns","Eaton","Blackwell","Dyer","Prince","Macdonald","Solomon","Guevara","Stafford","English","Hurst","Woodard","Cortes","Shannon","Kemp","Nolan",
"Mccullough","Merritt","Murillo","Moon","Salgado","Strong","Kline","Cordova","Barajas","Roach","Rosas","Winters","Jacobson","Lester","Knox","Bullock","Kerr",
"Leach","Meadows","Orr","Davila","Whitehead","Pruitt","Kent","Conway","Mckee","Barr","David","Dejesus","Marin","Berger","Mcintyre","Blankenship","Gaines",
"Palacios","Cuevas","Bartlett","Durham","Dorsey","Mccall","Odonnell","Stein","Browning","Stout","Lowery","Sloan","Mclean","Hendricks","Calhoun","Sexton",
"Chung","Gentry","Hull","Duarte","Ellison","Nielsen","Gillespie","Buck","Middleton","Sellers","Leblanc","Esparza","Hardin","Bradshaw","Mcintosh","Howe",
"Livingston","Frost","Glass","Morse","Knapp","Herman","Stark","Bravo","Noble","Spears","Weeks","Corona","Frederick","Buckley","Mcfarland","Hebert","Enriquez","Hickman","Quintero","Randolph",
"Schaefer","Walls","Trejo","House","Reilly","Pennington","Michael","Conrad","Giles","Benjamin","Crosby","Fitzpatrick","Donovan","Mays","Mahoney","Valentine",
"Raymond","Medrano","Hahn","Mcmillan","Small","Peck","Bentley","Felix","Lucero","Boyle","Hanna","Pace","Rush","Hurley","Harding","Mcconnell","Bernal",
"Nava","Ayers","Everett","Ventura","Avery","Pugh","Mayer","Bender","Shepard","Mcmahon","Landry","Case","Sampson","Moses","Magana","Blackburn","Dunlap",
"Gould","Duffy","Vaughan","Herring","Mckay","Espinosa","Rivers","Farley","Bernard","Ashley","Friedman","Potts","Truong","Costa","Correa","Blevins","Nixon",
"Clements","Fry","Delarosa","Best","Benton","Lugo","Portillo","Dougherty","Crane","Haley","Phan","Villalobos","Blanchard","Horne","Finley","Quintana",
"Lynn","Esquivel","Bean","Dodson","Mullen","Xiong","Hayden","Cano","Levy","Huber","Richmond","Moyer","Lim","Frye","Sheppard","Mccarty","Avalos","Booker",
"Waller","Parra","Woodward","Jaramillo","Krueger","Rasmussen","Brandt","Peralta","Donaldson","Stuart","Faulkner","Maynard","Galindo","Coffey","Estes",
"Sanford","Burch","Maddox","Vo","Oconnell","Vu","Andersen","Spence","Mcpherson","Church","Schmitt","Stanton","Leal","Cherry","Compton","Dudley","Sierra",
"Pollard","Alfaro","Hester","Proctor","Lu","Hinton","Novak","Good","Madden","Mccann","Terrell","Jarvis","Dickson","Reyna","Cantrell","Mayo","Branch","Hendrix",
"Rollins","Rowland","Whitney","Duke","Odom","Daugherty","Travis","Tang","Archer",
]

american_citys=["Alabama/Birmingham",
"Alasca/Anchorage",
"Arizona/Phoenix",
"Arkansas/Little Rock",
"Califórnia/Los Angeles",
"Colorado/Denver",
"Connecticut/Hartford",
"Delaware/Dover",
"Flórida/Miami",
"Geórgia/Atlanta",
"Havaí/Honolulu",
"Idaho/Boise",
"Illinois/Chicago",
"Indiana/Indianapolis",
"Iowa/Des Moines",
"Kansas/Wichita",
"Kentucky/Louisville",
"Louisiana/New Orleans",
"Maine/Portland",
"Maryland/Baltimore",
"Massachusetts/Boston",
"Michigan/Detroit",
"Minnesota/Minneapolis",
"Mississippi/Jackson",
"Missouri/Kansas City",
"Montana/Billings",
"Nebraska/Omaha",
"Nevada/Las Vegas",
"New Hampshire/Concord",
"Nova Jersey/Newark",
"Novo México/Albuquerque",
"Nova York/Nova Iorque",
"Carolina do Norte/Charlotte",
"Dakota do Norte/Bismarck",
"Ohio/Columbus",
"Oklahoma/Oklahoma City",
"Oregon/Portland",
"Pensilvânia/Filadélfia",
"Rhode Island/Providence",
"Carolina do Sul/Columbia",
"Dakota do Sul/Sioux Falls",
"Tennessee/Memphis",
"Texas/Houston",
"Utah/Salt Lake City",
"Vermont/Montpelier",
"Virgínia/Richmond",
"Washington/Seattle",
"Virgínia Ocidental/Charleston",
"Wisconsin/Milwaukee",
"Wyoming/Cheyenne",
"Arizona/Tucson",
"Califórnia/São Francisco",
"Colorado/Colorado Springs",
"Connecticut/New Haven",
"Flórida/Orlando",
"Geórgia/Savannah",
"Idaho/Nampa",
"Illinois/Springfield",
"Indiana/Fort Wayne",
"Iowa/Cedar Rapids",
"Kansas/Topeka",
"Kentucky/Lexington",
"Luisiana/Baton Rouge",
"Maine/Lewiston",
"Maryland/Annapolis",
"Massachusetts/Springfield",
"Michigan/Grand Rapids",
"Minnesota/Saint Paul",
"Mississippi/Gulfport",
"Missouri/Saint Louis",
"Montana/Missoula",
"Nebraska/Lincoln",
"Nevada/Reno",
"Nova Hampshire/Manchester",
"Nova Jersey/Jersey City",
"Novo México/Santa Fe",
"Nova York/Buffalo",
"Carolina do Norte/Raleigh",
"Dakota do Norte/Fargo",
"Ohio/Cleveland",
"Oklahoma/Tulsa",
"Oregon/Salem",
"Pensilvânia/Pittsburgh",
"Rhode Island/Newport",
"Carolina do Sul/Charleston",
"Dakota do Sul/Rapid City",
"Tennessee/Nashville",
"Texas/Dallas",
"Utah/West Valley City",
"Vermont/Burlington",
"Virgínia/Norfolk",
"Washington/Tacoma",
"Virgínia Ocidental/Morgantown",
"Wisconsin/Madison",
"Wyoming/Casper",
"Alabama/Mobile",
"Alasca/Fairbanks",
"Arizona/Tempe",
"Arkansas/Fayetteville",
"Califórnia/San Diego",
"Colorado/Fort Collins",
"Connecticut/Stamford",
"Delaware/Wilmington",
"Flórida/Tampa",
"Geórgia/Augusta",
"Havaí/Hilo",
"Idaho/Idaho Falls",
"Illinois/Peoria",
"Indiana/Fort Wayne",
"Iowa/Iowa City",
"Kansas/Overland Park",
"Kentucky/Lexington",
"Louisiana/Baton Rouge",
"Maine/Augusta",
"Maryland/Rockville",
"Massachusetts/Worcester",
"Michigan/Ann Arbor",
"Minnesota/Rochester",
"Mississippi/Biloxi",
"Missouri/Springfield",
"Montana/Missoula",
"Nebraska/Grand Island",
"Nevada/Henderson",
"New Hampshire/Manchester",
"Nova Jersey/Trenton",
"Novo México/Santa Fé",
"Nova York/Rochester",
"Carolina do Norte/Greensboro",
"Dakota do Norte/Grand Forks",
"Ohio/Cincinnati",
"Oklahoma/Norman",
"Oregon/Eugene",
"Pensilvânia/Allentown",
"Rhode Island/Cranston",
"Carolina do Sul/Greenville",
"Dakota do Sul/Aberdeen",
"Tennessee/Knoxville",
"Texas/Austin",
"Utah/Provo",
"Vermont/Rutland",
"Virgínia/Alexandria",
"Washington/Bellevue",
"Virgínia Ocidental/Huntington",
"Wisconsin/Green Bay",
"Wyoming/Rock Springs",
"Arizona/Glendale",
"Califórnia/San Jose",
"Colorado/Pueblo",
"Connecticut/New Britain",
"Flórida/St. Petersburg",
"Geórgia/Athens",
"Idaho/Meridian",
"Illinois/Naperville",
"Indiana/South Bend",
"Iowa/Davenport",
"Kansas/Manhattan",
"Kentucky/Owensboro",
"Luisiana/Lafayette",
"Maine/Bangor",
"Maryland/Gaithersburg",
"Massachusetts/Lowell",
"Michigan/Lansing",
"Minnesota/Duluth",
"Mississippi/Southaven",
"Missouri/Columbia",
"Montana/Bozeman",
"Nebraska/Kearney",
"Nevada/Paradise",
"Nova Hampshire/Nashua",
"Nova Jersey/Paterson",
"Novo México/Las Cruces",
"Nova York/Yonkers",
"Carolina do Norte/Winston-Salem",
"Dakota do Norte/Minot",
"Ohio/Dayton",
"Oklahoma/Broken Arrow",
"Oregon/Gresham",
"Pensilvânia/Erie",
"Rhode Island/Warwick",
"Carolina do Sul/Rock Hill",
"Dakota do Sul/Brookings",
"Tennessee/Chattanooga",
"Texas/San Antonio",
"Utah/Orem",
"Vermont/Montpelier",
"Virgínia/Newport News",
"Washington/Vancouver",
"Virgínia Ocidental/Parkersburg",
"Wisconsin/Kenosha",
"Wyoming/Gillette"]

american_ranks_army = {
    "Oficiais": ["General of the Army", "General", "Lieutenant General", "Major General", "Brigadier General", "Colonel", "Lieutenant Colonel", "Major", "Captain", "First Lieutenant", "Second Lieutenant"],
    "Suboficiais e Praças": ["Master Sergeant (M/Sgt.)", "First Sergeant (1st Sgt.)", "Technical Sergeant (T/Sgt.)", "Staff Sergeant (S/Sgt.)", "Sergeant (Sgt.)", "Corporal (Cpl.)", "Private First Class (Pfc.)", "Private / Specialist (Pvt.)"]
}

american_ranks_air = {
    "Oficiais": ["General of the Air Force", "General", "Lieutenant General", "Major General", "Brigadier General", "Colonel", "Lieutenant Colonel", "Major", "Captain", "First Lieutenant", "Second Lieutenant"],
    "Suboficiais e Praças": ["Chief Master Sergeant of the Air Force", "Chief Master Sergeant", "Senior Master Sergeant", "Master Sergeant", "Technical Sergeant", "Staff Sergeant", "Senior Airman", "Airman First Class",  "Airman","Airman Basic"]
}

american_ranks_navy = {
    "Oficiais": ["Fleet Admiral","Admiral","Vice Admiral","Rear Admiral","Commodore","Captain","Commander","Lieutenant Commander","Lieutenant","Lieutenant Junior Grade","Ensign"],
    "Suboficiais e Praças": ["Master Chief Petty Officer of the Navy","Master Chief Petty Officer","Senior Chief Petty Officer","Chief Petty Officer","Petty Officer First Class","Petty Officer Second Class","Petty Officer Third Class","Seaman","Seaman Apprentice","Seaman Recruit"]
}