# LiSTA DE NOMES E SOBRENOMES FRANCESES ESTADOS E CIDADES

french_names = ["Adam", "Alexandre", "Antoine", "Arthur", "Auguste", "Baptiste", "Benjamin", "Cédric", "Charles", "Clément", "Damien", "David",
"Édouard", "Étienne", "Fabien", "Florian", "Gabriel", "Gaspard", "Geoffroy", "Guillaume", "Hugo", "Isaac", "Jérôme", "Jonathan",
"Julien", "Kevin", "Léo", "Louis", "Lucas", "Marc", "Martin", "Mathias", "Maxime", "Nicolas", "Noé", "Olivier", "Paul", "Pierre",
"Quentin", "Raphaël", "Rémi", "Robin", "Samuel", "Sébastien", "Simon", "Théo", "Thomas", "Timothée", "Tristan", "Valentin",
"Victor", "Vincent", "Xavier", "Yann", "Yoann", "Zacharie", "Adrien", "André", "Anthony", "Arnaud", "Aurélien", "Benoît", "Camille",
"Cédric", "Cyril", "Daniel", "Denis", "Émile", "Éric", "François", "Frédéric", "Gaël", "Grégoire", "Hervé", "Hubert", "Jacques",
"Jean", "Jérémie", "Joël", "Joseph", "Jules", "Laurent", "Léon", "Lionel", "Loïc", "Lucien", "Manuel", "Marcel", "Michel", "Morgan",
"Nathan", "Olivier", "Patrice", "Philippe", "Régis", "René", "Sylvain", "Thierry", "Tristan", "Yannick", "Yves"]

french_surnames = ["Martin","Bernard","Robert","Richard","Durand","Dubois","Moreau","Simon","Laurent","Michel","Garcia","Thomas","Leroy","David","Morel",
"Roux","Girard","Fournier","Lambert","Lefebvre","Mercier","Blanc","Dupont","Faure","Bertrand","Morin","Garnier","Nicolas","Marie","Rousseau","Bonnet","Vincent",
"Henry","Masson","Robin","Martinez","Boyer","Muller","Chevalier","Denis","Meyer","Blanchard","Lemaire","Dufour","Gauthier","Vidal","Perez","Perrin","Fontaine",
"Joly","Jean","da Silva","Gautier","Roche","Roy","Pereira","Mathieu","Roussel","Duval","Guerin","Lopez","Rodriguez","Colin","Aubert","Lefevre","Marchand","Schmitt",
"Picard","Caron","Sanchez","Meunier","Gaillard","Louis","Nguyen","Lucas","Dumont","dos Santos","Brunet","Clement","Brun","Arnaud","Giraud","Barbier","Rolland",
"Charles","Hubert","Fernandes","Fabre","Moulin","Leroux","Dupuis","Guillaume","Roger","Paris","Guillot","Dupuy","Fernandez","Carpentier","Payet","Ferreira",
"Olivier","Philippe","Deschamps","Lacroix","Jacquet","Rey","Klein","Renaud","Baron","Leclerc","Royer","Berger","Bourgeois","Bertin","Petit","Adam","Daniel",
"Lemoine","Pierre","Francois","Goncalves","Benoit","Lecomte","Vasseur","Lebrun","Leblanc","Leclercq","Besson","Charpentier","Etienne","Jacob","Michaud","Maillard",
"Dumas","Monnier","Fleury","Aubry","Hamon","Renard","Chevallier","Guyot","Marty","Gomez","Andre","Le Roux","Boucher","Bailly","Pons","Renault","Julien","Huet",
"Riviere","Gonzalez","Reynaud","Collet","Bouvier","Millet","Rodrigues","Gerard","Bouchet","Schneider","Germain","Marchal","Martins","Breton","Cousin","Langlois",
"Perrot","Perrier","Le Gall","Noel","Pelletier","Mallet","Weber","Hoarau","Chauvin","Le Goff","Grondin","Antoine","Boulanger","Gilbert","Humbert","Guichard",
"Poulain","Collin","Tessier","Pasquier","Jacques","Lamy","da Costa","Alexandre","Perret","Poirier","Pascal","Gros","Buisson","Albert","Lopes","Ruiz","Lejeune",
"Cordier","Hernandez","Georges","Maillot","Delaunay","Laporte","Pichon","Voisin","Lemaitre","Launay","Lesage","Carlier","Ollivier","Gomes","Besnard","Camus",
"Coulon","Cohen","Charrier","Paul","Didier","Guillet","Guillou","Remy","Joubert","Bousquet","Verdier","Hoareau","Briand","Raynaud","Delmas","Coste","Blanchet","Marin","Lebreton","Leduc","Sauvage","Martel","Gaudin",
"Lebon","Rossi","Diallo","Delattre","Maury","Ribeiro","Bigot","Menard","Guillon","Thibault","Colas","Raymond","Delorme","Pineau","Joseph","Hardy","Berthelot",
"Allard","Lagarde","Ferrand","Valentin","Lenoir","Tran","Bonneau","Clerc","Godard","Tanguy","Brunel","Gilles","Imbert","Seguin","Jourdan""Alves","Bruneau",
"Bodin","Morvan","Vaillant","Marion","Devaux","Maurice","Courtois","Baudry","Chauvet","Prevost","Couturier","Turpin","Lefort","Lacombe","Favre","Maire","Barre",
"Riou","Allain","Lombard","Mary","Lacoste","Blin","Costa","Evrard","Thierry","Leveque","Loiseau","Navarro","Laroche","Bourdon","Texier","Carre","Levy","Toussaint",
"Grenier","Guilbert","Guibert","Chartier","Bonnin","Maillet","Benard","Jacquot","Auger","Vallet","Leconte","Bazin","Rousset","Fischer","Rocher","Normand",
"Descamps","Potier","Valette","Peltier","Duhamel","Wagner","Merle","Faivre","Barbe","Blondel","Pottier","Pinto","Maurin","Guyon","Vial","Martineau","Blot",
"Gallet","Foucher","Delage","Guy","Chauveau","Barthelemy","Fouquet","Boutin","Bouvet","Salmon","Rossignol","Neveu","Lemonnier","Marechal","Herve","Delahaye",
"Poncet","Bernier","Lafon","Teixeira","Chapuis","Pujol","Lecoq","Charbonnier","de Sousa","Laborde","Cros","Serre","Andrieu","Girault","Pruvost","Berthier",
"Grand","Sabatier","Boulay","Le Roy","Duclos","Martinet","Hebert","Maurel","Gervais","Dias","de Oliveira","Parent","Jourdain","Ali","Regnier","Marc","Diaz",
"Billard","Favier","Bellanger","Delannoy","Torres","Dubreuil","Becker","Doucet","Gras","Prigent","Rigaud","Samson","Masse","Cornu","Chambon","Mas","Fortin",
"Besse","Castel","Letellier","Ricard","Benoist","Poisson","Parmentier","Lepage","Boulet","Grandjean","Claude","Mendes","Bonhomme","Roques","Huguet","Comte",
"Pommier","Le Corre","Forestier","Drouet","Constant","Leblond","Jolly","Brault","Gosselin","Lacour","Rose","Prat","Geoffroy","Hamel","Tournier","Rault",
"Mounier","Ledoux","Marquet","Blondeau","Grange","Morand","Picot","Millot","Brossard","Laval","Merlin","Bocquet","Granger","Jung","Leleu","Levasseur","Guillemin",
"Armand","Barret","Mouton","Champion","Moreno","Bouquet","Keller","Bourdin","Cartier","Gimenez","Jamet","Lavigne","Combes","Said","Lelievre","Guillard",
"Berthet","Guillemot","Gibert","Leray","Gicquel","Ferry","Fort","Dumoulin","Provost","Basset","Papin","Terrier","Walter","Andrieux","Tellier","Jeanne",
"Bataille","Munoz","Jullien","Ramos","Prieur","Bouchard","Saunier","Bon","Chatelain","Foulon","Lasserre","Granier","Cochet","Mignot","Lang","Prost","Vernet",
"Kieffer","Madi","Gil","Jolivet","Vallee","Schmidt","Traore","Dijoux","Le Bihan","Weiss","Esnault","Vigneron","Vacher","Tissot","Dujardin","Pain","Soulier",
"Cadet","Couderc","Gabriel","Lavergne","Bois","Lefranc","Monier","Poulet","Le Guen","Peron","Oliveira","Jouve","Husson","Jouan","Gregoire","Barreau","Lemarchand",
"Arnould","Blaise","Mahe","Bourguignon","Cornet","Flament","Grosjean","Binet","Laine","Borel","Dupin","Pasquet","Abdou","Tardy","Lelong","Schwartz","Proust","Villard",
"Rouxel","Lallemand","Combe","Carvalho","Corre","Monteiro","Roth","Lecocq","Baudin","Mangin","Ragot","Bruno","Bayle","Bonin","Magnier","Beaumont","Rigal",
"Ducrocq","André","Aubin","Thiery","Grimaud","Labat","Bonnefoy","Roland","Bureau","Bauer","Brochard","Tavernier","Zimmermann","Chollet","Moreira","Wolff",
"Deshayes","Baudouin","Godefroy","Bastien","Montagne","Arnoux","Villain","Goujon","Galland","Labbe","Chevrier","Chabert","Bonnard","Cardon","Chretien","Babin",
"Bordes","Baudet","Jacquin","Lebeau","Simonet","Le Gal","Legrand","Lagrange","Caillaud","Boudet","Pierron","Pires","Lassalle","Parisot","Silva","Christophe",
"Maitre","Lesueur","Godet","Prevot","Faucher","Josse","Lafont","Oger","Sicard","Derrien","Sergent","Thiebaut","Foucault","Jacquemin","Ferrer","Avril","Correia",
"Piquet","Lefeuvre","Renou","Beaufils","Pellerin","Forest","Abadie","Pages","Abdallah","Alvarez","Ferrari","Techer","Duret","Hue","Delaporte","Le Berre",
"Le Floch","Guignard","Begue","Porte","Magne","Beck","Raynal","Gonthier","Louvet","Lalanne","Thuillier","Godin","Berton","Duchemin","Bailleul","Jarry",
"Stephan","Le Meur","George","Guitton","Verger","Camara","Salaun","Henri","Lamotte","Belin","Duprat","Guilbaud","Lauret","Le Bris","Saulnier","Boisson",
"Lapierre","Gaubert","Perron","Bisson","Clavel","Jan","Paillard","Boivin","Clain","Dupre","Marais","Latour","Astier","Charlet","Landais","Leonard","Mauger",
"Bour","Savary","Chateau","Molina","Boisseau","Vigouroux","Tison","Boutet","Diot","Bresson","Larue","Ba","Coulibaly","Guiraud","Brousse","Jeannin","Le Bras",
"Monnet","Soares","Payen","Duchesne","Blandin","Redon","Le Borgne","Miquel","Courtin","Leon","Serres","Renaudin","Gillot","Lecuyer","Berard","Bourgoin","Fayolle",
"Coudert","Simonnet","Gobert","Bontemps","Hamelin","Robinet","Bossard","Barraud","Thery","Caillet","Teyssier","Rouault","Chemin","Ferrier","Bardet","Morice",
"Janin","Gallois","Baudoin","Burel","Larcher","Mendy","Capelle","Delpech","Magnin","Bardin","Bouyer","Gonzales","Marcel","Prudhomme","Baptiste","Delarue",
"Lamarque","Machado","Loison","Malet","Baud","Devos","Gasnier","Sellier","Billon","Chopin","Gaultier","Collard","Dubourg","Billet","Sarrazin","Cottin","Lebas",
"Gosset","Schaeffer","Drouin","Jimenez","Janvier","Goupil","Tixier","Catherine","Chapelle","Calvet","Chabot","Garreau","Garcin","Auvray","Mayer","Jardin",
"Felix","Le Breton","Vieira","Costes","Ferre","Lhomme","Vergne","Gueguen","Loisel","Cuny","Alix","Dubos","Lavaud","Lahaye","Cormier","Alonso","Diop","Pastor",
"Chiron","Reboul","Constantin","Mace","Lemercier","Beauvais","Soler","Coutant","Genin","Ly","Hilaire","Dejean","Fourcade","Bastide","Froment","Mille","Charron",
"Roman","Fritsch","Guyard","Barthe","Guilloux","de Almeida","Mathis","Villette","Raimbault","Dupouy","Dubost","Delcroix","Lapeyre","Salomon","Bach","Desbois",
"Genet","Claudel","Page","Philippon","Beau","Bidault","Marteau","Bosc","Geffroy","Cellier","Manceau","Moine","Thevenet","Ndiaye","Ouvrard","Besnier","Deville",
"Choquet","Pierson","Chardon","Munier","Lallement","Moret","Auffret","Antunes","Collignon","Leloup","Tissier","Romain","Sorin","Anne","Rambaud","Viala","Haas",
"Mahieu","Koch","Amiot","Laffont","Vernier","Duriez","Vivier","Peter","Leclere","Pelissier","Duarte","Lamour","Landry","Rollin","Billaud","Sow","Bonnot","Michon",
"Sylvestre","Crouzet","Boulard","Vignon","Cazenave","Brisset","Braud","Reymond","Demange","Salles","Marquis","Laplace","Genty","Jaouen","Toure","Wang","Langlais",
"Laville","Braun","Mazet","Huard","Monin","Pernot","Gourdon","Durieux","Bru","Lafond","Dauphin","Peyre","Fraisse","Monteil","Claverie","Rio","Naudin","Delamare",
"Bacar","Olive","Clavier","Viel","Bellec","Arnal","Giroud","Merlet","Georget","Davy","Carton","Labrousse","Bachelet","Bianchi","Berthe","Barrier","Nicol",
"Cariou","Roch","Chen","Lacaze","Bourbon","Carrier","Gaucher","Fauvel","Lenormand","Rochette","Hugon","Emery","Toutain","Murat","Viguier","Bel","Achard","Lafitte",
"Nunes","James","Lafargue","France","Jean-Baptiste","Capron","Rondeau","Pollet","Bouton","Rivet","Cortes","Casanova","Cardoso","Girardot","Alain","Tisserand",
"Barry","Dubus","Barbet","Romero","Frey","Revel","Ho",
]

french_citys=["Île-de-France/Paris",
"Provença-Alpes-Côte d'Azur/Marselha",
"Auvergne-Rhône-Alpes/Lyon",
"Occitânia/Toulouse",
"Provença-Alpes-Côte d'Azur/Nice",
"País do Loire/Nantes",
"Grande Leste/Alsácia/Estrasburgo",
"Occitânia/Montpellier",
"Nova Aquitânia/Bordéus",
"Altos da França/Lille",
"Bretanha/Rennes",
"Grande Leste/Champagne-Ardenne/Reims",
"Normandia/Le Havre",
"Île-de-France/Cergy",
"Auvergne-Rhône-Alpes/Saint-Étienne",
"Provença-Alpes-Côte d'Azur/Toulon",
"País do Loire/Angers",
"Auvergne-Rhône-Alpes/Grenoble",
"Borgonha-Franco-Condado/Dijon",
"Occitânia/Nîmes",
"Provença-Alpes-Côte d'Azur/Aix-en-Provence",
"Île-de-France/Saint-Quentin-en-Yvelines",
"Bretanha/Brest",
"País do Loire/Le Mans",
"Altos da França/Amiens",
"Centro-Vale do Loire/Tours",
"Nova Aquitânia/Limoges",
"Auvérnia-Ródano-Alpes/Clermont-Ferrand",
"Auvérnia-Ródano-Alpes/Villeurbanne",
"Borgonha-Franco-Condado/Besançon",
"Centro-Vale do Loire/Orléans",
"Grande Leste/Grande Leste/Metz",
"Normandia/Rouen",
"Auvérnia-Ródano-Alpes/Mulhouse",
"Occitânia/Perpignan",
"Normandia/Caen",
"Ilha de França/Boulogne-Billancourt",
"Grande Leste/Grande Leste/Nancy",
"Ilha de França/Argenteuil",
"Ilha de França/Saint-Denis",
"Altos da França/Roubaix",
"Altos da França/Tourcoing",
"Ilha de França/Montreuil",
"Provença-Alpes-Côte d'Azur/Avignon",
"Ilha de França/Asnières-sur-Seine",
"Ilha de França/Nanterre",
"Nova Aquitânia/Poitiers",
"Île-de-France/Versalhes",
"Ilha de França/Créteil",
"Ilha de França/Vitry-sur-Seine",
"Ilha de França/Colombes",
"Ilha de França/Aulnay-sous-Bois",
"Nova Aquitânia/La Rochelle",
"Ilha de França/Champigny-sur-Marne",
"Ilha de França/Saint-Maur-des-Fossés",
"Provença-Alpes-Côte d'Azur/Antibes",
"Altos da França/Calais",
"Occitânia/Béziers",
"Altos da França/Dunkerque",
"Provença-Alpes-Côte d'Azur/Cannes",
"País do Loire/Saint-Nazaire",
"Grande Leste/Alsácia/Colmar",
"Auvérnia-Ródano-Alpes/Valence",
"Bretanha/Quimper",
"Altos da França/Villeneuve-d'Ascq",
"Centro-Vale do Loire/Bourges",
"Provença-Alpes-Côte d'Azur/La Seyne-sur-Mer",
"Bretanha/Lorient",
"Reunião/Le Tampon",
"Nova Aquitânia/Niort",
"Altos da França/Saint-Quentin",
"Ilha de França/Sarcelles",
"Nova Aquitânia/Pau",
"País do Loire/Cholet",
"Auvérnia-Ródano-Alpes/Annecy",
"Auvérnia-Ródano-Alpes/Chambéry",
"Grande Leste/Champagne-Ardenne/Charleville-Mézières",
"Altos da França/Cambrai",
"Bretanha/Saint-Brieuc",
"Ilha de França/Creil",
"Île-de-France/Cergy-Pontoise",
"Córsega/Ajaccio",
"Altos da França/Boulogne-sur-Mer",
"Occitânia/Castres",
"Altos da França/Valenciennes",
"Provença-Alpes-Côte d'Azur/Istres",
"Provença-Alpes-Côte d'Azur/Salon-de-Provence",
"Normandia/Évreux",
"Île-de-France/Massy",
"Île-de-France/Meaux",
"Île-de-France/Ivry-sur-Seine",
"Auvérnia-Ródano-Alpes/Venissieux",
"Ilha de França/Clichy",
"Île-de-France/Levallois-Perret",
"País do Loire/La Roche-sur-Yon",
"Île-de-France/Choisy-le-Roi",
"Borgonha-Franco-Condado/Chalon-sur-Saône",
"Borgonha-Franco-Condado/Nevers",
"Île-de-France/Bondy",
"Île-de-France/Noisy-le-Grand"]

french_ranks_army = {
    "Oficiais": ["Aspirant", "Tenente", "Capitaine", "Chef de Bataillon", "Lieutenant-Colonel", "Colonel", "Général de Brigade",
                 "Général de Division", "Général de Corps d'Armée", "Général d'Armée"],
    "Suboficiais e Praças": ["Sergent", "Sergent-Chef", "Sergent-Major", "Adjudant", "Adjudant-Chef", "Soldat",
                             "Soldat de 1re Classe", "Caporal", "Caporal de 1re Classe"]
}

french_ranks_air = {
    "Oficiais": ["Aspirant", "Sous-Lieutenant", "Lieutenant", "Capitaine", "Commandant", "Lieutenant-Colonel", "Colonel",
                 "Général de Brigade Aérienne", "Général de Division Aérienne", "Général de Corps Aérien", "Général d'Armée Aérienne"],
    "Suboficiais e Praças": ["Sergent", "Sergent-Chef", "Sergent-Major", "Adjudant", "Adjudant-Chef", "Soldat", "Soldat de 1re Classe",
                             "Caporal", "Caporal de 1re Classe"]
}

french_ranks_navy = {
    "Oficiais": ["Enseigne de Vaisseau de 2e Classe", "Enseigne de Vaisseau de 1re Classe", "Lieutenant de Vaisseau",
                 "Capitaine de Corvette", "Capitaine de Frégate", "Capitaine de Vaisseau", "Contre-Amiral", "Vice-Amiral", "Amiral"],
    "Suboficiais e Praças": ["Maître", "Premier Maître", "Maître Principal", "Second Maître", "Maître de 1re Classe",
                             "Matelot", "Matelot de 1re Classe", "Quartier-Maître", "Quartier-Maître de 1re Classe"]
}
