# LiSTA DE NOMES E SOBRENOMES JAPONES ESTADOS E CIDADES
japanese_names = ["Takashi", "Hiroshi", "Akihito", "Satoru", "Isamu"]

japanese_surnames = ["Sato","Suzuki","Tanaka","Watanabe","Takahashi","Ito","Yamamoto","Nakamura","Kobayashi","Saito","Kato","Yoshida","Yamada","Sasaki",
"Matsumoto","Yamaguchi","Inoue","Kimura","Shimizu","Hayashi","Abe","Ono","Mori","Nakajima","Hashimoto","Ikeda","Yamazaki","Ishikawa","Yamashita","Ogawa",
"Ishii","Sakamoto","Goto","Maeda","Okada","Hasegawa","Fujita","Kondo","Sakai","Murakami","Ota","Kikuchi","Ueda","Arai","Endo","Aoki","Takeuchi","Nakano",
"Fujii","Fukuda","Kaneko","Nishimura","Okamoto","Nakagawa","Fujiwara","Miura","Harada","Matsuda","Kojima","Morita","Tamura","Nakayama","Ishida","Wada",
"Shibata","Masuda","Hara","Ando","Uchida","Shimada","Yokoyama","Miyamoto","Honda","Koyama","Takagi","Miyazaki","Taniguchi","Ueno","Imai","Maruyama","Kudo",
"Sugiyama","Fujimoto","Kawamura","Kono","Murata","Kubota","Hirano","Otsuka","Noguchi","Takeda","Matsui","Sakurai","Chiba","Ida","Kubo","Sugawara","Kinoshita",
"Takada","Nomura","Kawai","Sano","Sugimoto","Ichikawa","Matsuo","Oya","Nagai","Furukawa","Adachi","Nakata","Onishi","Yoshikawa","Iwasaki","Yasuda","Mizuno",
"Kawaguchi","Tsuchiya","Fukushima","Hino","Nishida","Kitamura","Yamauchi","Nishikawa","Takano","Kawakami","Ozawa","Hamada","Komatsu","Seki","Oda","Nakanishi",
"Igarashi","Hirata","Morimoto","Hattori","Higashi","Akiyama","Kawasaki","Tomita","Tsuji","Sawada","Tanabe","Iwata","Yoshimura","Yamanaka","Taguchi","Oshima",
"Higuchi","Okubo","Hirose","Ishihara","Matsuoka","Baba","Ohashi","Asano","Yoshioka","Yano","Matsushita","Araki","Koike","Hoshino","Noda","Ohara","Sudo",
"Kawashima","Uemura","Ozaki","Matsuura","Naito","Kumagai","Iwamoto","Kuroda","Hori","Nagata","Matsumura","Kurihara","Ogura","Nishiyama","Hayakawa","Hirai",
"Mochizuki","Doi","Yoshino","Yokota","Ishibashi","Koga","Katayama","Sakaguchi","Osawa","Sekiguchi","Kamata","Hagihara","Oishi","Miyata","Konno","Kodama",
"Uehara","Minami","Konishi","Shoji","Fukui","Koizumi","Yagi","Shinohara","Tajima","Honma","Nagashima","Furuya","Omori","Kitagawa","Miyake","Ogata","Narita",
"Okumura","Oka","Matsubara","Kano","Matsunaga","Uchiyama","Nakai","Kataoka","Sugiura","Okuda","Sakata","Makino","Okazaki","Hirayama","Nakao","Izumi","Sekine",
"Takayama","Nakazawa","Shibuya","Shiraishi","Terada","Kuwahara","Imamura","Aoyama","Nagano","Sakuma","Onodera","Tada","Amano","Okamura","Daisen","Tsunoda",
"Nishi","Toyoda","Tsukamoto","Kawamoto","Konpon","Oba","Shirai","Murayama","Muto","Miyashita","Asai","Kasai","Izuka","Kamiya","Taketa","Morishita","Mizutani",
"Oikawa","Ijima","Enomoto","Maekawa","Okabe","Kanda","Miyagawa","Ogasawara","Nagao","Okawa","Tani","Inagaki","Wakabayashi","Osada","Inaba","Moriyama","Tashiro",
"Horiuchi","Tamaki","Ishizuka","Mikami","Morikawa","Kishimoto","Nakatani","Yamane","Kanazawa","Usui","Eguchi","Okano","Kaneda","Nishio","Arakawa","Toda",
"Hosokawa","Kanai","Hoshi","Otake","Ochiai","Yoshizawa","Nakahara","Hirota","Hatakeyama","Muramatsu","Machida","Tsuda","Matsuzaki","Tsutsumi","Takizawa",
"Saeki","Iwai","Ide","Kawabata","Sugita","Nagasawa","Takei","Miyoshi","Yoneda","Fukumoto","Kurokawa","Matsuyama","Kishi","Hotta","Nishino","Kai","Yamagishi",
"Takemoto","Miki","Kurosawa","Tachibana","Nishioka","Kosaka","Miyazawa","Fujisawa","Taiboku","Horie","Mukai","Takashima","Tominaga","Umeda","Kuroki","Nonaka",
"Kasahara","Obata","Miyagi","Kawata","Yoshimoto","Sakakibara","Nozaki","Shinta","Aizawa","Furuta","Suda","Yamakawa","Murai","Ozeki","Matsushima","Akimoto",
"Omura","Tokunaga","Okuyama","Yanagisawa","Iguchi","Taira","Nishimoto","Tsuchita","Hata","Oshiro","Shimoda","Kajiwara","Onuma","Takenaka","Kinjo","Otani",
"Shindo","Uno","Kita","Ogino","Kunai","Takemura","Yasui","Asada","Yajima","Yoshiwara","Shigeki","Okuno","Takeshita","Toyama","Ino","Tsukada","Hatano",
"Ouchi","Fujikawa","Komori","Otsuki","Nagaoka","Kitano","Ishiguro","Kurita","Fukazawa","Nozawa","Fujino","Tanigawa","San-Rin","Fujioka","Niwa","Hika",
"Kawara","Fujimura","Negishi","Hyugawa","Shimomura","Kamei","Kan","Miyahara","Deguchi","Sonoda","Aoyagi","Yokoi","Hidaka","Shimazaki","Shinoda","Sanson",
"Haga","Inada","Nakamoto","Hiramatsu","Seto","Maki","Fukuoka","Moriya","Tahara","Tsutsui","Fukunaga","Eto","Shimura","Mizoguchi","Hayashida","Ninomiya","Shimamura",
"Isobe","Takai","Kurata","Shinozaki","Kitajima","Ohira","Tezuka","Takase","Koide","Iwase","Yuasa","Senda","Kitahara","Irie","Yanagida","Kido","Numata",
"Seo","Yamaoka","Horiguchi","Katsumata","Nagase","Kawano","Hosoya","Soma","Ishiyama","Hamano","Horikawa","Kawase","Ochi","Tsuruta","Nanba","Hatake",
"Kashiwagi","Sugihara","Shima","Hamaguchi","Hiraoka","Kawahara","Terashima","Ikegami","Aihara","Nagayama","Fukuhara","Matsuzawa","Miyajima","Katagiri",
"Manabe","Shiba","Morioka","Akita","Tanimoto","Hanada","Naikai","Asakura","Kawabe","Murase","Torii","Matsuno","Mishima","Nishihara","Tahata","Hatanaka",
"Takamatsu","Tsuboi","Yoshii","Mitsui","Ishizaki","Masaki","Kageyama","Aida""Haraguchi","Tsujimoto","Imaizumi","Tokuda","Shintani","Komiya","Akiba",
"Yamagata","Naka","Oi","Taue","Enzan","Shirakawa","Otomo","Senken","Furusawa","Mimura","Sekiya","Yoneyama","Minakawa","Usami","Koyanagi","Ueki","Kihara",
"Yoshinaga","Ogiwara","Inomata","Hosoda","Nishisawa","Mitani","Fukuyama","Kishida","Hosaka","Satake","Kamiyama","Kiuchi","Hashizume","Hirabayashi","Kaji",
"Toshima","Nasu","Nomoto","Shioda","Kawauchi","San-Kyo","Nakasato","Kuriyama","Komura","Otsubo","Yonezawa","Iwashita","Matsukawa","Hayasaka","Kimoto",
"Imura","Kawada","Takimoto","Kawahata","Hamazaki","Kuno","Aikawa","Tsuzuki","Kameyama","Horii","Teramoto","Ihara","Handa","Yanagi","Kagawa","Ishiwata",
"Ichimura","Onuki","Osaki","Kusano","Muraoka","Otsu","Iwabuchi","Shiga","Someya","Sakashita","Okura","Kida","Tomioka","Sugaya","Kameda","Nakane","Namiki",
"Hirasawa","Sone","Mita","Risshaku","Wakamatsu","Mashiko","Suijo","Sugai","Mizuguchi","Nara","Ohata","Uematsu","Kaku","Ichihara","Fujimori","Tamai","Hamamoto",
"Oe","Sekawa","Fujisaki","Kiyono","Aragaki","Naiya","Takiguchi","Koda","Hashiguchi","Kitayama","Iwasa","Fukaya","Miyadokorono","Misawa","Mihara","Ueyama",
"Arima","Arita","Yabe","Iwaki","Komuro","Kitazawa","Gezan","Izawa","Shibazaki","Naruse","Koken","Sakagami","Takaoka","Maehara","Itagaki","Tabuchi","Tagawa",
"Hida","Tatsumi","Akutsu","Okita","Hase","Hirao","Ebara","Takayanagi","Kokubo","Ebihara","Itakura","Shina","Matsugi","Nokami","Oku","Takao","Inui","Makita",
"Ichinose","Fujiki","Unno","Bando","Ishimoto","Hasebe","Ishigaki","Takahara","Yamano","Shigeta","Sanjo","Kashima","Yamajiro","Horikoshi","Tsukahara","Imada",
"Kanaya","Igawa","Kadowaki","Kanamori","Suwa","Hosoi","Hosono","Kogure","Sugimura","Onoda","Yoda","Kitada","Shishido","Kosugi","Kuroiwa","Hiratsuka",
"Suenaga","Umehara","Nishitani","Soga","Otaki","Egawa","Motohashi","Shimokawa","Akagi","Nohara","Fuse","Kuramochi","Iwanaga","Kanayama","Moritani","Sawai",
"Mizushima","Akamatsu","Asou","Imoto","Tasaki","Ishimaru","Shimazu","Owada","Tachikawa","Takanashi","Miyano","Sawa","Sanada","Sakano","Nagamine","Suganuma",
"Imanishi","Oguma","Kasuya","Tsushima","Ikuta","Miyawaki","Umemoto","Nihei","Nakabayashi","Nakaya","Shimabukuro","Nishiguchi","Kawamata","Kusunoki","Anzai",
"Shiotani","Ezaki","Komine","Tokashi","Kusaka","Tabata","Suka","Kazama","Suiden","Kume","Sagawa","Yanase","Kadota","Takasaki","Komiyama","Shibayama","Sako",
"Terasawa","Goda","Yanai","Taki","Ishizaka","Moriguchi","Urata","Ashida","Sugino","Ikegaya","Kuramoto","Obayashi","Moriwaki","Takeyama","Saijo","Masui",
"Kase","Mano","Sunagawa","Iwama","Osanai","Dobashi","Tomizawa","Yaguchi","Nagasaki","Akasaka","Yuki","Meguro","Mine","Sanshi","Akashi","Odaka","Uda",
"Tanno","Fukata","Yamato","Yanagawa","Chino","Kanemaru","Maejima","Hatta","Terao","Itahashi","Utsunomiya","Hakucho","Kadoya","Tsuruoka","Karasawa","Oki",
"Onoe","Osaka","Isono","Naganuma","Nagasaka","Hama","Takehara","Kumasawa","Ikemoto","Kanzaki","Okajima","Oshita","Kiyota","Omata","Yata","Asanuma","Asagawa",
"Kosuga","Amamiya","Ariga","Nimi","Kanbara","Umemura","Urano","Kamino","Kusumoto","Hibino","Tateno","Ishizawa","Kobori","Nojima","Nagahama","Kuribayashi",
"Kuwata","Umezu","Yanagihara","Kawanishi","Morinaga","Udagawa","Nishiwaki","Ikeuchi","Suyama","Nishishima","Teshima","Yokoo","Uesugi","Takaya","Yokokawa",
"Miyasaka","Natsume","Shida","Agatsuma","Kanbayashi","Aono","Kashiwabara","Sakiyama","Nakatsuka","Kawagoe","Ko","Waki","Shiomi","Iwasawa","Wakita","Funaki",
"Takita","Munakata","Kijima","Kagami","Kusakabe","Fujishima","Kokubu","Kakinuma","Mochida","Takakura","Kin","Tokita","Ishino","Nose","Hojo","Fukuchi",
"Katsuta","Morii","Hyodo","Sakurada","Nagae","Totsuka","Onda","Furuyama","Maeno","Honjo","Honson","Tanimura","Sawamura","Kobe","Sasakawa","Okayama",
"Okawara","Oguri","Umesawa","Shiroki","Shunjitsu","Shimamoto","Gunji","Takigawa","Hanaoka","Uchimura","Tojo","Kawana","Shinkai","Hanawa","Koguchi",
"Nagatomo","Araya","Eda","Wakayama","Ura","Ishigura","Miyasato","Yazawa","Atsumi","Ima","Morishima","Minato","Sunaga","Mizumoto","Sueyoshi","Ukai",
"Kojo","Saka","Isozaki","Tadokoro","Hirokawa","Kumada","Tazawa","Sagara","Shigematsu","Sakamaki","Omae","Akabane","Oura","Takezawa","Muraki","Motoki",
"Funakoshi","Onigashira","Shiozawa","Nishii","Minegishi","Fukai","Tajiri","Hiraga","Honzan","Teranishi","Sasahara","Kurahashi","Serizawa","Yoshizaki",
"Nishiura","Hikita","Hanai","Omi","Hiramoto","Tamada","Fukuzawa","Shirota","Shinbo","Tono","Kumamoto","Furuhashi","Yahagi","Kariya","Yoshitake","Takahata",
"Hiyama","Ujiie","Urabe","Hatakenaka","Kumakura","Noro","Chinen","Iwatani","Masuyama","Otaka","Nanbu","Kajita","Teraoka","Yonekura",
]

japan_citys = [
"Tóquio, Kanto","Yokohama, Kanto","Osaka, Kinki","Nagoya, Chubu","Kyoto, Kinki","Kobe, Kinki","Sapporo, Hokkaido","Fukuoka, Kyushu","Kawasaki, Kanto","Hiroshima, Chugoku","Sendai, Tohoku","Kitakyushu, Kyushu","Chiba, Kanto","Sakai, Kinki","Kumamoto, Kyushu","Okayama, Chugoku",
"Sagamihara, Kanto","Hamamatsu, Chubu","Shizuoka, Chubu","Niigata, Chubu","Hachioji, Kanto","Kagoshima, Kyushu","Himeji, Kinki","Matsuyama, Shikoku","Naha, Okinawa","Kurashiki, Chugoku","Shizuoka, Chubu","Oita, Kyushu","Kanazawa, Hokuriku","Amagasaki, Kinki","Yokosuka, Kanto","Nagasaki, Kyushu",
"Kofu, Chubu","Kawasaki, Kanto","Kobe, Kinki","Kumamoto, Kyushu","Hachinohe, Tohoku","Matsudo, Kanto","Ichikawa, Kanto","Utsunomiya, Kanto","Matsuyama, Shikoku","Koriyama, Tohoku","Maebashi, Kanto","Urawa, Kanto","Tokorozawa, Kanto","Hakodate, Hokkaido","Akita, Tohoku","Takamatsu, Shikoku",
"Koshigaya, Kanto","Hirakata, Kinki","Yamagata, Tohoku","Fukuyama, Chugoku","Toyota, Chubu","Gifu, Chubu","Toyohashi, Chubu","Toyama, Hokuriku","Ichinomiya, Chubu","Wakayama, Kinki","Fukushima, Tohoku","Otsu, Kinki","Miyazaki, Kyushu","Tokushima, Shikoku","Kagoshima, Kyushu","Morioka, Tohoku",
"Akashi, Kinki","Miyakonojo, Kyushu","Iwaki, Tohoku","Nagano, Chubu","Okazaki, Chubu","Kurume, Kyushu","Gifu, Chubu","Yamato, Kanto","Ibaraki, Kanto","Fukui, Hokuriku","Mito, Kanto","Asahikawa, Hokkaido","Takasaki, Kanto","Fujisawa, Kanto","Okinawa, Okinawa","Oita, Kyushu","Ichihara, Kanto",
"Hiratsuka, Kanto","Fujisawa, Kanto","Toyonaka, Kinki","Fukuyama, Chugoku","Machida, Kanto","Fujimi, Kanto","Chigasaki, Kanto","Iwata, Chubu","Higashihiroshima, Chugoku","Yamaguchi, Chugoku","Otsuki, Kanto","Tokuyama, Chugoku","Nagareyama, Kanto","Hitachi, Kanto","Akishima, Kanto","Isesaki, Kanto",
"Atsugi, Kanto","Komaki, Chubu","Tachikawa, Kanto","Tottori, Chugoku","Nara, Kinki","Tokushima, Shikoku","Kure, Chugoku","Anjo, Chubu","Tomakomai, Hokkaido","Naruto, Shikoku","Yamato, Kanto","Maizuru, Kinki","Ageo, Kanto","Iwatsuki, Kanto","Koganei, Kanto","Saku, Kanto","Ome, Kanto","Akune, Kyushu","Chikushino, Kyushu",
"Shimonoseki, Chugoku","Nagaoka, Chubu","Kakogawa, Kinki","Toyooka, Kinki","Kamakura, Kanto","Isehara, Kanto","Chofu, Kanto","Kasugai, Chubu","Fukaya, Kanto","Uji, Kinki","Nishinomiya, Kinki","Ogori, Kyushu","Kiryu, Kanto","Urayasu, Kanto","Neyagawa, Kinki","Abiko, Kanto","Akita, Tohoku","Ichinoseki, Tohoku",
"Yamagata, Tohoku","Koriyama, Tohoku","Nagaoka, Tohoku","Morioka, Tohoku","Aizuwakamatsu, Tohoku","Sendai, Tohoku","Iwaki, Tohoku","Fukushima, Tohoku","Goshogawara, Tohoku","Odate, Tohoku","Misawa, Tohoku","Kitami, Hokkaido","Asahikawa, Hokkaido","Sapporo, Hokkaido","Hakodate, Hokkaido","Muroran, Hokkaido",
"Obihiro, Hokkaido","Tomakomai, Hokkaido","Kushiro, Hokkaido","Abashiri, Hokkaido","Wakkanai, Hokkaido","Nemuro, Hokkaido","Kushiro, Hokkaido","Hakodate, Hokkaido","Ishinomaki, Tohoku","Ishinomaki, Tohoku","Aomori, Tohoku","Hachinohe, Tohoku","Hirosaki, Tohoku","Akita, Tohoku","Morioka, Tohoku","Yamagata, Tohoku",
"Sendai, Tohoku","Fukushima, Tohoku","Koriyama, Tohoku","Niigata, Chubu","Toyama, Chubu","Kanazawa, Chubu","Fukui, Chubu","Nagano, Chubu","Shizuoka, Chubu","Hamamatsu, Chubu","Gifu, Chubu","Nagoya, Chubu","Mito, Kanto","Utsunomiya, Kanto","Takasaki, Kanto","Chiba, Kanto","Tokyo, Kanto","Yokohama, Kanto","Sagamihara, Kanto",
"Kawasaki, Kanto","Saitama, Kanto","Kawaguchi, Kanto","Maebashi, Kanto","Urayasu, Kanto","Kofu, Kanto","Yokosuka, Kanto","Kumagaya, Kanto","Iwaki, Kanto","Ichikawa, Kanto","Machida, Kanto","Hiratsuka, Kanto","Odawara, Kanto","Chigasaki, Kanto","Atsugi, Kanto","Hachioji, Kanto","Nerima, Kanto","Akishima, Kanto",
"Fuchu, Kanto","Tachikawa, Kanto","Musashino, Kanto","Ome, Kanto","Mitaka, Kanto","Tokorozawa, Kanto","Koshigaya, Kanto","Fujisawa, Kanto","Kawasaki, Kanto","Yokohama, Kanto","Saitama, Kanto","Chiba, Kanto","Nagoya, Chubu","Toyota, Chubu","Okazaki, Chubu","Gifu, Chubu","Shizuoka, Chubu","Hamamatsu, Chubu","Niigata, Chubu",
"Kanazawa, Chubu","Toyama, Chubu","Fukui, Chubu","Kyoto, Kinki","Osaka, Kinki","Kobe, Kinki","Nara, Kinki","Wakayama, Kinki","Nagoya, Kinki","Kyoto, Kinki","Osaka, Kinki","Kobe, Kinki","Himeji, Kinki","Nara, Kinki","Wakayama, Kinki","Tottori, Chugoku","Matsue, Chugoku","Okayama, Chugoku","Hiroshima, Chugoku","Yamaguchi, Chugoku",
"Tokushima, Shikoku","Kochi, Shikoku","Matsuyama,Shikoku","Takamatsu, Shikoku","Tokushima, Shikoku","Matsuyama, Shikoku","Kochi, Shikoku","Fukuoka, Kyushu","Kitakyushu, Kyushu",
]