# LiSTA DE NOMES E SOBRENOMES JAPONES ESTADOS E CIDADES
japanese_names = ["大翔 / ヒロト Hiroto",
"陽斗 / ハルト Haruto",
"拓海 / タクミ Takumi",
"颯太 / ソウタ Sota",
"悠斗 / ユウト Yuto",
"翔太 / ショウタ Shota",
"陽向 / ヒナタ Hinata",
"悠真 / ユウマ Yuma",
"瑛太 / エイタ Eita",
"翔平 / ショウヘイ Shohei",
"蓮斗 / レント Rento",
"陽翔 / ヒカル Hikaru",
"蒼空 / ソラ Sora",
"颯人 / ソウト Souto",
"翔 / ショウ Sho",
"拓斗 / タクト Takuto",
"悠翔 / ユウキ Yuuki",
"大和 / ヤマト Yamato",
"瑛斗 / エイト Eito",
"陽太 / ハルタ Haruta",
"悠人 / ユウト Yuto",
"翔真 / ショウマ Shoma",
"蓮 / レン Ren",
"陽大 / ヒロヒロ Hirohiro",
"蒼太 / ソウタ Souta",
"翔太郎 / ショウタロウ Shotaro",
"拓也 / タクヤ Takuya",
"悠 / ユウ Yuu",
"大樹 / タイキ Taiki",
"瑛大 / エイタイ Eitai",
"陽向 / ヒナタ Hinata",
"悠太 / ユウタ Yuta",
"翔平 / ショウヘイ Shohei",
"蓮斗 / レント Rento",
"陽翔 / ヒカル Hikaru",
"蒼空 / ソラ Sora",
"颯人 / ソウト Souto",
"翔 / ショウ Sho",
"拓斗 / タクト Takuto",
"悠翔 / ユウキ Yuuki",
"大和 / ヤマト Yamato",
"瑛斗 / エイト Eito",
"陽太 / ハルタ Haruta",
"悠人 / ユウト Yuto",
"翔真 / ショウマ Shoma",
"蓮 / レン Ren",
"陽大 / ヒロヒロ Hirohiro",
"蒼太 / ソウタ Souta",
"翔太郎 / ショウタロウ Shotaro",
"拓也 / タクヤ Takuya",
"悠 / ユウ Yuu",
"大樹 / タイキ Taiki",
"瑛大 / エイタイ Eitai",
"陽斗 / ハルト Haruto",
"拓海 / タクミ Takumi",
"颯太 / ソウタ Sota",
"悠斗 / ユウト Yuto",
"翔太 / ショウタ Shota",
"陽向 / ヒナタ Hinata",
"悠真 / ユウマ Yuma",
"瑛太 / エイタ Eita",
"翔平 / ショウヘイ Shohei",
"蓮斗 / レント Rento",
"陽翔 / ヒカル Hikaru",
"蒼空 / ソラ Sora",
"颯人 / ソウト Souto",
"翔 / ショウ Sho",
"拓斗 / タクト Takuto",
"悠翔 / ユウキ Yuuki",
"大和 / ヤマト Yamato",
"瑛斗 / エイト Eito",
"陽太 / ハルタ Haruta",
"悠人 / ユウト Yuto",
"翔真 / ショウマ Shoma",
"蓮 / レン Ren",
"陽大 / ヒロヒロ Hirohiro",
"蒼太 / ソウタ Souta",
"翔太郎 / ショウタロウ Shotaro",
"拓也 / タクヤ Takuya",
"悠 / ユウ Yuu",
"大樹 / タイキ Taiki",
"瑛大 / エイタイ Eitai",
"陽斗 / ハルト Haruto",
"拓海 / タクミ Takumi",
"颯太 / ソウタ Sota",
"悠斗 / ユウト Yuto",
"翔太 / ショウタ Shota",
"陽向 / ヒナタ Hinata",
"悠真 / ユウマ Yuma",
"瑛太 / エイタ Eita",
"翔平 / ショウヘイ Shohei",
"蓮斗 / レント Rento",
"陽翔 / ヒカル Hikaru",
"蒼空 / ソラ Sora",
"颯人 / ソウト Souto",
"翔 / ショウ Sho",
"拓斗 / タクト Takuto",
"悠翔 / ユウキ Yuuki",
"大和 / ヤマト Yamato",
"瑛斗 / エイト Eito",
"陽太 / ハルタ Haruta",
"悠人 / ユウト Yuto",
"翔真 / ショウマ Shoma",
"蓮 / レン Ren",
"陽大 / ヒロヒロ Hirohiro",
"蒼太 / ソウタ Souta",
"翔太郎 / ショウタロウ Shotaro",
"拓也 / タクヤ Takuya",
"悠 / ユウ Yuu",
"大樹 / タイキ Taiki",
"瑛大 / エイタイ Eitai"]

japanese_surnames = ["Sato","Suzuki","Tanaka","Watanabe","Takahashi","Ito","Yamamoto","Nakamura","Kobayashi","Saito","Kato","Yoshida","Yamada","Sasaki",
"Matsumoto","Yamaguchi","Inoue","Kimura","Shimizu","Hayashi","Abe","Ono","Mori","Nakajima","Hashimoto","Ikeda","Yamazaki","Ishikawa","Yamashita","Ogawa",
"Ishii","Sakamoto","Goto","Maeda","Okada","Hasegawa","Fujita","Kondo","Sakai","Murakami","Ota","Kikuchi","Ueda","Arai","Endo","Aoki","Takeuchi","Nakano",
"Fujii","Fukuda","Kaneko","Nishimura","Okamoto","Nakagawa","Fujiwara","Miura","Harada","Matsuda","Kojima","Morita","Tamura","Nakayama","Ishida","Wada",
"Shibata","Masuda","Hara","Ando","Uchida","Shimada","Yokoyama","Miyamoto","Honda","Koyama","Takagi","Miyazaki","Taniguchi","Ueno","Imai","Maruyama","Kudo",
"Sugiyama","Fujimoto","Kawamura","Kono","Murata","Kubota","Hirano","Otsuka","Noguchi","Takeda","Matsui","Sakurai","Chiba","Ida","Kubo","Sugawara","Kinoshita",
"Takada","Nomura","Kawai","Sano","Sugimoto","Ichikawa","Matsuo","Oya","Nagai","Furukawa","Adachi","Nakata","Onishi","Yoshikawa","Iwasaki","Yasuda","Mizuno",
"Kawaguchi","Tsuchiya","Fukushima","Hino","Nishida","Kitamura","Yamauchi","Nishikawa","Takano","Kawakami","Ozawa","Hamada","Komatsu","Seki","Oda","Nakanishi",
"Igarashi","Hirata","Morimoto","Hattori","Higashi","Akiyama","Kawasaki","Tomita","Tsuji","Sawada","Tanabe","Iwata","Yoshimura","Yamanaka","Taguchi","Oshima",
"Higuchi","Okubo","Hirose","Ishihara","Matsuoka","Baba","Ohashi","Asano","Yoshioka","Yano","Matsushita","Araki","Koike","Hoshino","Noda","Ohara","Sudo",
"Kawashima","Uemura","Ozaki","Matsuura","Naito","Kumagai","Iwamoto","Kuroda","Hori","Nagata","Matsumura","Kurihara","Ogura","Nishiyama","Hayakawa","Hirai",
"Mochizuki","Doi","Yoshino","Yokota","Ishibashi","Koga","Katayama","Sakaguchi","Osawa","Sekiguchi","Kamata","Hagihara","Oishi","Miyata","Konno","Kodama",
"Uehara","Minami","Konishi","Shoji","Fukui","Koizumi","Yagi","Shinohara","Tajima","Honma","Nagashima","Furuya","Omori","Kitagawa","Miyake","Ogata","Narita",
"Okumura","Oka","Matsubara","Kano","Matsunaga","Uchiyama","Nakai","Kataoka","Sugiura","Okuda","Sakata","Makino","Okazaki","Hirayama","Nakao","Izumi","Sekine",
"Takayama","Nakazawa","Shibuya","Shiraishi","Terada","Kuwahara","Imamura","Aoyama","Nagano","Sakuma","Onodera","Tada","Amano","Okamura","Daisen","Tsunoda",
"Nishi","Toyoda","Tsukamoto","Kawamoto","Konpon","Oba","Shirai","Murayama","Muto","Miyashita","Asai","Kasai","Izuka","Kamiya","Taketa","Morishita","Mizutani",
"Oikawa","Ijima","Enomoto","Maekawa","Okabe","Kanda","Miyagawa","Ogasawara","Nagao","Okawa","Tani","Inagaki","Wakabayashi","Osada","Inaba","Moriyama","Tashiro",
"Horiuchi","Tamaki","Ishizuka","Mikami","Morikawa","Kishimoto","Nakatani","Yamane","Kanazawa","Usui","Eguchi","Okano","Kaneda","Nishio","Arakawa","Toda",
"Hosokawa","Kanai","Hoshi","Otake","Ochiai","Yoshizawa","Nakahara","Hirota","Hatakeyama","Muramatsu","Machida","Tsuda","Matsuzaki","Tsutsumi","Takizawa",
"Saeki","Iwai","Ide","Kawabata","Sugita","Nagasawa","Takei","Miyoshi","Yoneda","Fukumoto","Kurokawa","Matsuyama","Kishi","Hotta","Nishino","Kai","Yamagishi",
"Takemoto","Miki","Kurosawa","Tachibana","Nishioka","Kosaka","Miyazawa","Fujisawa","Taiboku","Horie","Mukai","Takashima","Tominaga","Umeda","Kuroki","Nonaka",
"Kasahara","Obata","Miyagi","Kawata","Yoshimoto","Sakakibara","Nozaki","Shinta","Aizawa","Furuta","Suda","Yamakawa","Murai","Ozeki","Matsushima","Akimoto",
"Omura","Tokunaga","Okuyama","Yanagisawa","Iguchi","Taira","Nishimoto","Tsuchita","Hata","Oshiro","Shimoda","Kajiwara","Onuma","Takenaka","Kinjo","Otani",
"Shindo","Uno","Kita","Ogino","Kunai","Takemura","Yasui","Asada","Yajima","Yoshiwara","Shigeki","Okuno","Takeshita","Toyama","Ino","Tsukada","Hatano",
"Ouchi","Fujikawa","Komori","Otsuki","Nagaoka","Kitano","Ishiguro","Kurita","Fukazawa","Nozawa","Fujino","Tanigawa","San-Rin","Fujioka","Niwa","Hika",
"Kawara","Fujimura","Negishi","Hyugawa","Shimomura","Kamei","Kan","Miyahara","Deguchi","Sonoda","Aoyagi","Yokoi","Hidaka","Shimazaki","Shinoda","Sanson",
"Haga","Inada","Nakamoto","Hiramatsu","Seto","Maki","Fukuoka","Moriya","Tahara","Tsutsui","Fukunaga","Eto","Shimura","Mizoguchi","Hayashida","Ninomiya","Shimamura",
"Isobe","Takai","Kurata","Shinozaki","Kitajima","Ohira","Tezuka","Takase","Koide","Iwase","Yuasa","Senda","Kitahara","Irie","Yanagida","Kido","Numata",
"Seo","Yamaoka","Horiguchi","Katsumata","Nagase","Kawano","Hosoya","Soma","Ishiyama","Hamano","Horikawa","Kawase","Ochi","Tsuruta","Nanba","Hatake",
"Kashiwagi","Sugihara","Shima","Hamaguchi","Hiraoka","Kawahara","Terashima","Ikegami","Aihara","Nagayama","Fukuhara","Matsuzawa","Miyajima","Katagiri",
"Manabe","Shiba","Morioka","Akita","Tanimoto","Hanada","Naikai","Asakura","Kawabe","Murase","Torii","Matsuno","Mishima","Nishihara","Tahata","Hatanaka",
"Takamatsu","Tsuboi","Yoshii","Mitsui","Ishizaki","Masaki","Kageyama","Aida""Haraguchi","Tsujimoto","Imaizumi","Tokuda","Shintani","Komiya","Akiba",
"Yamagata","Naka","Oi","Taue","Enzan","Shirakawa","Otomo","Senken","Furusawa","Mimura","Sekiya","Yoneyama","Minakawa","Usami","Koyanagi","Ueki","Kihara",
"Yoshinaga","Ogiwara","Inomata","Hosoda","Nishisawa","Mitani","Fukuyama","Kishida","Hosaka","Satake","Kamiyama","Kiuchi","Hashizume","Hirabayashi","Kaji",
"Toshima","Nasu","Nomoto","Shioda","Kawauchi","San-Kyo","Nakasato","Kuriyama","Komura","Otsubo","Yonezawa","Iwashita","Matsukawa","Hayasaka","Kimoto",
"Imura","Kawada","Takimoto","Kawahata","Hamazaki","Kuno","Aikawa","Tsuzuki","Kameyama","Horii","Teramoto","Ihara","Handa","Yanagi","Kagawa","Ishiwata",
"Ichimura","Onuki","Osaki","Kusano","Muraoka","Otsu","Iwabuchi","Shiga","Someya","Sakashita","Okura","Kida","Tomioka","Sugaya","Kameda","Nakane","Namiki",
"Hirasawa","Sone","Mita","Risshaku","Wakamatsu","Mashiko","Suijo","Sugai","Mizuguchi","Nara","Ohata","Uematsu","Kaku","Ichihara","Fujimori","Tamai","Hamamoto",
"Oe","Sekawa","Fujisaki","Kiyono","Aragaki","Naiya","Takiguchi","Koda","Hashiguchi","Kitayama","Iwasa","Fukaya","Miyadokorono","Misawa","Mihara","Ueyama",
"Arima","Arita","Yabe","Iwaki","Komuro","Kitazawa","Gezan","Izawa","Shibazaki","Naruse","Koken","Sakagami","Takaoka","Maehara","Itagaki","Tabuchi","Tagawa",
"Hida","Tatsumi","Akutsu","Okita","Hase","Hirao","Ebara","Takayanagi","Kokubo","Ebihara","Itakura","Shina","Matsugi","Nokami","Oku","Takao","Inui","Makita",
"Ichinose","Fujiki","Unno","Bando","Ishimoto","Hasebe","Ishigaki","Takahara","Yamano","Shigeta","Sanjo","Kashima","Yamajiro","Horikoshi","Tsukahara","Imada",
"Kanaya","Igawa","Kadowaki","Kanamori","Suwa","Hosoi","Hosono","Kogure","Sugimura","Onoda","Yoda","Kitada","Shishido","Kosugi","Kuroiwa","Hiratsuka",
"Suenaga","Umehara","Nishitani","Soga","Otaki","Egawa","Motohashi","Shimokawa","Akagi","Nohara","Fuse","Kuramochi","Iwanaga","Kanayama","Moritani","Sawai",
"Mizushima","Akamatsu","Asou","Imoto","Tasaki","Ishimaru","Shimazu","Owada","Tachikawa","Takanashi","Miyano","Sawa","Sanada","Sakano","Nagamine","Suganuma",
"Imanishi","Oguma","Kasuya","Tsushima","Ikuta","Miyawaki","Umemoto","Nihei","Nakabayashi","Nakaya","Shimabukuro","Nishiguchi","Kawamata","Kusunoki","Anzai",
"Shiotani","Ezaki","Komine","Tokashi","Kusaka","Tabata","Suka","Kazama","Suiden","Kume","Sagawa","Yanase","Kadota","Takasaki","Komiyama","Shibayama","Sako",
"Terasawa","Goda","Yanai","Taki","Ishizaka","Moriguchi","Urata","Ashida","Sugino","Ikegaya","Kuramoto","Obayashi","Moriwaki","Takeyama","Saijo","Masui",
"Kase","Mano","Sunagawa","Iwama","Osanai","Dobashi","Tomizawa","Yaguchi","Nagasaki","Akasaka","Yuki","Meguro","Mine","Sanshi","Akashi","Odaka","Uda",
"Tanno","Fukata","Yamato","Yanagawa","Chino","Kanemaru","Maejima","Hatta","Terao","Itahashi","Utsunomiya","Hakucho","Kadoya","Tsuruoka","Karasawa","Oki",
"Onoe","Osaka","Isono","Naganuma","Nagasaka","Hama","Takehara","Kumasawa","Ikemoto","Kanzaki","Okajima","Oshita","Kiyota","Omata","Yata","Asanuma","Asagawa",
"Kosuga","Amamiya","Ariga","Nimi","Kanbara","Umemura","Urano","Kamino","Kusumoto","Hibino","Tateno","Ishizawa","Kobori","Nojima","Nagahama","Kuribayashi",
"Kuwata","Umezu","Yanagihara","Kawanishi","Morinaga","Udagawa","Nishiwaki","Ikeuchi","Suyama","Nishishima","Teshima","Yokoo","Uesugi","Takaya","Yokokawa",
"Miyasaka","Natsume","Shida","Agatsuma","Kanbayashi","Aono","Kashiwabara","Sakiyama","Nakatsuka","Kawagoe","Ko","Waki","Shiomi","Iwasawa","Wakita","Funaki",
"Takita","Munakata","Kijima","Kagami","Kusakabe","Fujishima","Kokubu","Kakinuma","Mochida","Takakura","Kin","Tokita","Ishino","Nose","Hojo","Fukuchi",
"Katsuta","Morii","Hyodo","Sakurada","Nagae","Totsuka","Onda","Furuyama","Maeno","Honjo","Honson","Tanimura","Sawamura","Kobe","Sasakawa","Okayama",
"Okawara","Oguri","Umesawa","Shiroki","Shunjitsu","Shimamoto","Gunji","Takigawa","Hanaoka","Uchimura","Tojo","Kawana","Shinkai","Hanawa","Koguchi",
"Nagatomo","Araya","Eda","Wakayama","Ura","Ishigura","Miyasato","Yazawa","Atsumi","Ima","Morishima","Minato","Sunaga","Mizumoto","Sueyoshi","Ukai",
"Kojo","Saka","Isozaki","Tadokoro","Hirokawa","Kumada","Tazawa","Sagara","Shigematsu","Sakamaki","Omae","Akabane","Oura","Takezawa","Muraki","Motoki",
"Funakoshi","Onigashira","Shiozawa","Nishii","Minegishi","Fukai","Tajiri","Hiraga","Honzan","Teranishi","Sasahara","Kurahashi","Serizawa","Yoshizaki",
"Nishiura","Hikita","Hanai","Omi","Hiramoto","Tamada","Fukuzawa","Shirota","Shinbo","Tono","Kumamoto","Furuhashi","Yahagi","Kariya","Yoshitake","Takahata",
"Hiyama","Ujiie","Urabe","Hatakenaka","Kumakura","Noro","Chinen","Iwatani","Masuyama","Otaka","Nanbu","Kajita","Teraoka","Yonekura",
]

japan_citys = [("北海道 (Hokkaido)", "札幌市 (Sapporo)"),
    ("青森県 (Aomori)", "青森市 (Aomori)"),
    ("岩手県 (Iwate)", "盛岡市 (Morioka)"),
    ("宮城県 (Miyagi)", "仙台市 (Sendai)"),
    ("秋田県 (Akita)", "秋田市 (Akita)"),
    ("山形県 (Yamagata)", "山形市 (Yamagata)"),
    ("福島県 (Fukushima)", "福島市 (Fukushima)"),
    ("茨城県 (Ibaraki)", "水戸市 (Mito)"),
    ("栃木県 (Tochigi)", "宇都宮市 (Utsunomiya)"),
    ("群馬県 (Gunma)", "前橋市 (Maebashi)"),
    ("埼玉県 (Saitama)", "さいたま市 (Saitama)"),
    ("千葉県 (Chiba)", "千葉市 (Chiba)"),
    ("東京都 (Tokyo)", "東京市 (Tokyo)"),
    ("神奈川県 (Kanagawa)", "横浜市 (Yokohama)"),
    ("新潟県 (Niigata)", "新潟市 (Niigata)"),
    ("富山県 (Toyama)", "富山市 (Toyama)"),
    ("石川県 (Ishikawa)", "金沢市 (Kanazawa)"),
    ("福井県 (Fukui)", "福井市 (Fukui)"),
    ("山梨県 (Yamanashi)", "甲府市 (Kofu)"),
    ("長野県 (Nagano)", "長野市 (Nagano)"),
    ("静岡県 (Shizuoka)", "静岡市 (Shizuoka)"),
    ("愛知県 (Aichi)", "名古屋市 (Nagoya)"),
    ("三重県 (Mie)", "津市 (Tsu)"),
    ("滋賀県 (Shiga)", "大津市 (Otsu)"),
    ("京都府 (Kyoto)", "京都市 (Kyoto)"),
    ("大阪府 (Osaka)", "大阪市 (Osaka)"),
    ("兵庫県 (Hyogo)", "神戸市 (Kobe)"),
    ("奈良県 (Nara)", "奈良市 (Nara)"),
    ("和歌山県 (Wakayama)", "和歌山市 (Wakayama)"),
    ("鳥取県 (Tottori)", "鳥取市 (Tottori)"),
    ("島根県 (Shimane)", "松江市 (Matsue)"),
    ("岡山県 (Okayama)", "岡山市 (Okayama)"),
    ("広島県 (Hiroshima)", "広島市 (Hiroshima)"),
    ("山口県 (Yamaguchi)", "山口市 (Yamaguchi)"),
    ("徳島県 (Tokushima)", "徳島市 (Tokushima)"),
    ("香川県 (Kagawa)", "高松市 (Takamatsu)"),
    ("愛媛県 (Ehime)", "松山市 (Matsuyama)"),
    ("高知県 (Kochi)", "高知市 (Kochi)"),
    ("福岡県 (Fukuoka)", "福岡市 (Fukuoka)"),
    ("佐賀県 (Saga)", "佐賀市 (Saga)"),
    ("長崎県 (Nagasaki)", "長崎市 (Nagasaki)"),
    ("熊本県 (Kumamoto)", "熊本市 (Kumamoto)"),
    ("大分県 (Oita)", "大分市 (Oita)"),
    ("宮崎県 (Miyazaki)", "宮崎市 (Miyazaki)"),
    ("鹿児島県 (Kagoshima)", "鹿児島市 (Kagoshima)"),
    ("沖縄県 (Okinawa)", "那覇市 (Naha)")]

japan_ranks_army = {"Oficiais": [""],
    "Suboficiais e Praças": [""]}

japan_ranks_air = {"Oficiais": [""],
    "Suboficiais e Praças": [""]}

japan_ranks_navy = {"Oficiais": [""],
    "Suboficiais e Praças": [""]}