# LiSTA DE NOMES E SOBRENOMES iNGLESES ESTADOS E CIDADES

uk_names = ["Aaren","Aaron","Abe","Abel","Abner","Abraham","Abram","Ace","Adair","Adam","Addison","Aden","Adolph","Adrian","Aidan","Aiden","Ainsley",
"Al","Alan","Alban","Albert","Albin","Alden","Aldous","Alec","Alex","Alexander","Alexis","Alf","Alfie","Alfred","Algar","Alger","Algernon","Allan","Allen",
"Allyn","Aloysius","Alpha","Alphonso","Alphonzo","Alton","Alva","Alvin","Ambrose","Amery","Amias","Amos","Amyas","Anderson","Andie","Andre","Andrew","Andy","Angel",
"Angus","Ansel","Anselm","Anson","Anthony","Anton","Antony","Archibald","Archie","Arden","Aric","Ariel","Arlen","Arlie","Arlo","Arn","Arnie","Arnold",
"Arron","Art","Arthur","Arvel","Ash","Asher","Ashley","Ashton","Aston","Astor","Auberon","Aubrey","Audley","August","Augustine","Austen","Austin","Austyn",
"Averill","Avery","Axel","Aydan","Ayden","Aylmer","Azaria","Bailey","Baldwin","Balfour","Barclay","Barnabas","Barney","Barret","Barrett","Barrie","Barry",
"Bart","Bartholomew","Basil","Baxter","Beau","Beaumont","Beauregard","Ben","Benedict","Benj","Benjamin","Benji","Benjy","Bennett","Bennie","Benny","Benson",
"Bentley","Benton","Bernard","Bernie","Berny","Berry","Bert","Bertie","Bertram","Bertrand","Bevan","Beverly","Bevis","Biff","Bill","Billie","Billy","Bishop",
"Blaine","Blair","Blake","Blaze","Blythe","Bob","Bobbie","Bobby","Boniface","Booker","Boyce","Boyd","Gage","Gale","Galen","Gallagher","Garfield","Garland",
"Garnet","Garnett","Garret","Garrett","Garrick","Garry","Garth","Gary","Gavin","Gayelord","Gayle","Gaylord","Geffrey","Gene","Geoff","Geoffrey","Geordie",
"George","Georgie","Gerald","Gerard","German","Gerrard","Gerry","Gervase","Gib","Gideon","Giffard","Gil","Gilbert","Giles","Gilroy","Gladwin","Gladwyn",
"Glanville","Glen","Glenn","Goddard","Godfrey","Goodwin","Gord","Gorden","Gordie","Gordon","Gordy","Gore","Grady","Graeme","Graham","Grahame","Grant",
"Granville","Gray","Grayson","Greer","Greg","Gregg","Gregory","Grenville","Gresham","Grey","Greyson","Grier","Griffin","Grosvenor","Grover","Gus","Guy",
"Gyles","Hadley","Hadyn","Hal","Hale","Hall","Hallam","Hamilton","Hammond","Hank","Happy","Harding","Hardy","Harlan","Harland","Harley","Harlow","Harmon",
"Harold","Harper","Harris","Harrison","Harry","Hartley","Harve","Harvey","Harvie","Haven","Hayden","Haywood","Headley","Heath","Hector","Hedley","Henderson",
"Henry","Herb","Herbert","Herbie","Herman","Herschel","Hershel","Hervey","Hewie","Hiram","Holden","Hollis","Homer","Horace","Horatio","Howard","Howie",
"Hoyt","Hubert","Hudson","Huey","Hugh","Hughie","Hugo","Humbert","Humphrey","Humphry","Hunter","Hyram","Ian","Iggy","Ike","Ilbert","Indiana","Indigo",
"Ingram","Inigo","Ira","Irvin","Irvine","Irving","Irwin","Isaac","Isador","Isadore","Isaiah","Isiah","Isidore","Israel","Issac","Issy","Ivan","Izzy",
"Jace","Jack","Jackie","Jackson","Jacob","Jade","Jaden","Jadyn","Jaiden","Jake","James","Jamey","Jamie","Jamison","Jared","Jarod","Jaron","Jarred","Jarrett",
"Jarrod","Jarvis","Jason","Jasper","Jaxon","Jaxson","Jay","Jayce","Jaycob","Jayden","Jaydon","Jaylen","Jaylin","Jaymes","Jayson","Jeb","Jed","Jeff","Jefferson",
"Jeffery","Jeffrey","Jeffry","Jem","Jemmy","Jepson","Jerald","Jere","Jeremiah","Jeremy","Jericho","Jermaine","Jerold","Jerome","Jerrard","Jerred","Jerrod",
"Jerrold","Jerry","Jervis","Jess","Jesse","Jessie","Jett","Jewel","Jewell","Jim","Jimi","Jimmie","Jimmy","Jo","Joby","Jody","Joe","Joel","Joey","John",
"Johnathan","Johnathon","Johnie","Johnnie","Johnny","Jojo","Jolyon","Jon","Jonah","Jonathan","Jonathon","Jonny","Jools","Jordan","Jordon","Joseph","Josh",
"Joshua","Josiah","Joss","Joyce","Judd","Jude","Jules","Julian","Julius","Julyan","Junior","Justice","Justin","Justy","Kade","Kaden","Kaeden","Kaiden","Kaleb",
"Kam","Kameron","Kane","Kaolin","Karl","Kasey","Kayden","Kean","Keane","Keaton","Keefe","Keegan","Kegan","Keiran","Keith","Kelan","Kelcey","Kelley","Kelly",
"Kelsey","Kelvin","Kemp","Ken","Kendal","Kendall","Kendrick","Kenelm","Kenith","Kennard","Kennedy","Kenneth","Kennith","Kenny","Kenrick","Kent","Kenton",
"Kenyon","Kenzie","Kermit","Kerry","Kester","Kev","Kevan","Kevin","Kevyn","Kian","Kiaran","Kiefer","Kieran","Kieron","Kim","Kimball","King","Kingsley",
"Kingston","Kip","Kipling","Kirby","Kirk","Kit","Knox","Koby","Kodey","Kody","Kolby","Kole","Konnor","Korbin","Korey","Kory","Kris","Kristopher","Kurt",
"Kurtis","Kyle","Kyler","Kynaston","Lacey","Lachlan","Lacy","Laird","Lake","Lamar","Lambert","Lamont","Lance","Landen","Landon","Lane","Lanford","Langdon",
"Lanny","Larrie","Larry","Lauren","Laurence","Robbie","Robby","Robert","Robin","Rocky","Rod","Roddy","Roderick","Rodge","Rodger","Rodney","Rodolph","Roger",
"Roland","Rolf","Rolland","Rollo","Rolo","Rolph","Roly","Roman","Ron","Ronald","Ronnie","Ronny","Roosevelt","Rorie","Rory","Roscoe","Ross","Roswell","Rowan",
"Rowland","Rowley","Roy","Royal","Royale","Royce","Roydon","Royle","Rube","Rudolph","Rudy","Rudyard","Rufus","Rupert","Russ","Russel","Russell","Rusty","Ryan",
"Ryder","Ryker","Rylan","Ryley","Sacheverell","Sage","Sal","Sam","Sammie","Sammy","Sampson","Samson","Samuel","Sandford","Sandy","Sanford","Sasha","Satchel",
"Sawyer","Saxon","Schuyler","Scot","Scott","Scottie","Scotty","Sean","Sebastian","Sefton","Selby","Selwyn","September","Sequoia","Seth","Seward","Seymour",
"Shad","Shane","Shannon","Shanon","Shaquille","Shaun","Shawn","Shayne","Sheard","Shel","Shelby","Sheldon","Shelley","Shelly","Shelton","Sheridan","Sherman",
"Sherwood","Shirley","Sid","Sidney","Sigmund","Silas","Silver","Silvester","Simon","Sinclair","Skylar","Skyler","Slade","Sly","Smith","Solomon","Sonnie",
"Sonny","Sparrow","Spencer","Spike","Stace","Stacey","Stacy","Stafford","Stan","Stanford","Stanley","Ste","Steph","Stephen","Sterling","Steve","Steven",
"Stevie","Stew","Stewart","Stirling","Storm","Stu","Stuart","Sullivan","Syd","Sydney","Sylvester","Tad","Taegan","Talbot","Talon","Tanner","Tate","Tatton",
"Tayler","Taylor","Teagan","Ted","Teddy","Temple","Tennyson","Terance","Terell","Terence","Terrance","Terrell","Terrence","Terry","Terry","Tex","Thad","Thaddeus",
"Thane","Theo","Theobald","Theodore","Thom","Thomas","Thorburn","Thorley","Thornton","Thurstan","Tibby","Tiger","Tim","Timmy","Timothy","Titus","Tobias",
"Tobin","Toby","Tod","Todd","Tom","Tommie","Tommy","Tony","Topher","Torin","Trace","Tracey","Tracy","Trafford","Tranter","Travers","Travis","Trent","Trenton",
"Trev","Trevelyan","Trevor","Trey","Tristan","Tristen","Tristin","Triston","Troy","Trueman","Truman","Tucker","Ty","Tye","Tylar","Tyler","Tylor","Tyrell",
"Tyron","Tyrone","Tyrrell","Tyson","Ulric","Ulysses","Upton","Val","Valentine","Van","Vance","Vaughan","Vaughn","Vere","Vergil","Vern","Vernon","Vic","Victor",
"Vin","Vinal","Vince","Vincent","Vinnie","Vinny","Virgil","Wade","Waldo","Walker","Wallace","Wallis","Wally","Walt","Walter","Walton","Ward","Wardell",
"Warner","Warren","Warrick","Warwick","Washington","Wat","Wayland","Waylon","Wayne","Webster","Weldon","Wendell","Wes","Wesley","Westley","Weston","Whitaker",
"Whitney","Wil","Wilbur","Wilburn","Wiley","Wilf","Wilford","Wilfred","Wilfrid","Wilkie","Will","Willard","William","Willie","Willis","Willoughby","Willy",
"Wilmer","Wilson","Wilton","Windsor","Winfred","Winslow","Winston","Winthrop","Winton","Wisdom","Wolf","Wolfe","Woodrow","Woody","Wright","Wyatt","Wynne",
"Wystan","Xander","Xavier","Xavior","Xzavier","Yale","Yancy","Yorick","York","Zac","Zach","Zachariah","Zachary","Zachery","Zack","Zackary","Zackery","Zak",
"Zander","Zane","Zavier","Zechariah",]

uk_surnames = ["Smith","Jones","Williams","Taylor","Brown","Davies","Evans","Wilson","Thomas","Johnson","Roberts","Robinson","Thompson","Wright","Walker",
"White","Edwards","Hughes","Green","Hall","Lewis","Harris","Clarke","Patel","Jackson","Wood","Turner","Martin","Cooper","Hill","Ward","Morris","Moore",
"Clark","Lee","King","Baker","Harrison","Morgan","Allen","James","Scott","Phillips","Watson","Davis","Parker","Price","Bennett","Young","Griffiths","Mitchell",
"Kelly","Cook","Carter","Richardson","Bailey","Collins","Bell","Shaw","Murphy","Miller","Cox","Richards","Khan","Marshall","Anderson","Simpson","Ellis",
"Adams","Singh","Begum","Wilkinson","Foster","Chapman","Powell","Webb","Rogers","Gray","Mason","Ali","Hunt","Hussain","Campbell","Matthews","Owen","Palmer",
"Holmes","Mills","Barnes","Knight","Lloyd","Butler","Russell","Barker","Fisher","Stevens","Jenkins","Murray","Dixon","Harvey","Graham","Pearson","Ahmed",
"Fletcher","Walsh","Kaur","Gibson","Howard","Andrews","Stewart","Elliott","Reynolds","Saunders","Payne","Fox","Ford","Pearce","Day","Brooks","West","Lawrence",
"Cole","Atkinson","Bradley","Spencer","Gill","Dawson","Ball","Burton","O’Brien","Watts","Rose","Booth","Perry","Ryan","Grant","Wells","Armstrong","Francis",
"Rees","Hayes","Hart","Hudson","Newman","Barrett","Webster","Hunter","Gregory","Carr","Lowe","Page","Marsh","Riley","Dunn","Woods","Parsons","Berry","Stone",
"Reid","Holland","Hawkins","Harding","Porter","Robertson","Newton","Oliver","Reed","Kennedy","Williamson","Bird","Gardner","Shah","Dean","Lane","Cooke",
"Bates","Henderson","Parry","Burgess","Bishop","Walton","Burns","Nicholson","Shepherd","Ross","Cross","Long","Freeman","Warren","Nicholls","Hamilton","Byrne",
"Sutton","Mcdonald","Yates","Hodgson","Robson","Curtis","Hopkins","O’Connor","Harper","Coleman","Watkins","Moss","Mccarthy","Chambers","O’Neill","Griffin",
"Sharp","Hardy","Wheeler","Potter","Osborne","Johnston","Gordon","Doyle","Wallace","George","Jordan","Hutchinson","Rowe","Burke","May","Pritchard","Gilbert",
"Willis","Higgins","Read","Miles","Stevenson","Stephenson","Hammond","Arnold","Buckley","Walters","Hewitt","Barber","Nelson","Slater","Austin","Sullivan",
"Whitehead","Mann","Frost","Lambert","Stephens","Blake","Akhtar","Lynch","Goodwin","Barton","Woodward","Thomson","Cunningham","Quinn","Barnett","Baxter",
"Bibi","Clayton","Nash","Greenwood","Jennings","Holt","Kemp","Poole","Gallagher","Bond","Stokes","Tucker","Davidson","Fowler","Heath","Norman","Middleton",
"Lawson","Banks","French","Stanley","Jarvis","Gibbs","Ferguson","Hayward","Carroll","Douglas","Dickinson","Todd","Barlow","Peters","Lucas","Knowles","Hartley",
"Miah","Simmons","Morton","Alexander","Field","Morrison","Norris","Townsend","Preston","Hancock","Thornton","Baldwin","Burrows","Briggs","Parkinson","Reeves",
"Macdonald","Lamb","Black","Abbott","Sanders","Thorpe","Holden","Tomlinson","Perkins","Ashton","Rhodes","Fuller","Howe","Bryant","Vaughan","Dale","Davey",
"Weston","Bartlett","Whittaker","Davison","Kent","Skinner","Birch","Morley","Daniels","Glover","Howell","Cartwright","Pugh","Humphreys","Goddard","Brennan",
"Wall","Kirby","Bowen","Savage","Bull","Wong","Dobson","Smart","Wilkins","Kirk","Fraser","Duffy","Hicks","Patterson","Bradshaw","Little","Archer","Warner",
"Waters","O’Sullivan","Farrell","Brookes","Atkins","Kay","Dodd","Bentley","Flynn","John","Schofield","Short","Haynes","Wade","Butcher","Henry","Sanderson",
"Crawford","Sheppard","Bolton","Coates","Giles","Gould","Houghton","Gibbons","Pratt","Manning","Law","Hooper","Noble","Dyer","Rahman","Clements","Moran",
"Sykes","Chan","Doherty","Connolly","Joyce","Franklin","Hobbs","Coles","Herbert","Steele","Kerr","Leach","Winter","Owens","Duncan","Naylor","Fleming","Horton",
"Finch","Fitzgerald","Randall","Carpenter","Marsden","Browne","Garner","Pickering","Hale","Dennis","Vincent","Chadwick","Chandler","Sharpe","Nolan","Lyons",
"Hurst","Collier","Peacock","Howarth","Faulkner","Rice","Pollard","Welch","Norton","Gough","Sinclair","Blackburn","Bryan","Conway","Power","Cameron","Daly",
"Allan","Hanson","Gardiner","Boyle","Myers","Turnbull","Wallis","Mahmood","Sims","Swift","Iqbal","Pope","Brady","Chamberlain","Rowley","Tyler","Farmer",
"Metcalfe","Hilton","Godfrey","Holloway","Parkin","Bray","Talbot","Donnelly","Nixon","Charlton","Benson","Whitehouse","Barry","Hope","Lord","North","Storey",
"Connor","Potts","Bevan","Hargreaves","Mclean","Mistry","Bruce","Howells","Hyde","Parkes","Wyatt","Fry","Lees","O’Donnell","Craig","Forster","Mckenzie","Humphries",
"Mellor","Carey","Ingram","Summers","Leonard",
]

uk_citys=[]

uk_ranks_army = {"Oficiais": [""],
    "Suboficiais e Praças": [""]}

uk_ranks_air = {"Oficiais": [""],
    "Suboficiais e Praças": [""]}

uk_ranks_navy = {"Oficiais": [""],
    "Suboficiais e Praças": [""]}